//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Disci_Hekim_Program.HekimServis {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HekimListe", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class HekimListe : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int HekimIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HekimAdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HekimSoyadField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int HekimID {
            get {
                return this.HekimIDField;
            }
            set {
                if ((this.HekimIDField.Equals(value) != true)) {
                    this.HekimIDField = value;
                    this.RaisePropertyChanged("HekimID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string HekimAd {
            get {
                return this.HekimAdField;
            }
            set {
                if ((object.ReferenceEquals(this.HekimAdField, value) != true)) {
                    this.HekimAdField = value;
                    this.RaisePropertyChanged("HekimAd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string HekimSoyad {
            get {
                return this.HekimSoyadField;
            }
            set {
                if ((object.ReferenceEquals(this.HekimSoyadField, value) != true)) {
                    this.HekimSoyadField = value;
                    this.RaisePropertyChanged("HekimSoyad");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="HekimServis.HekimSoap")]
    public interface HekimSoap {
        
        // CODEGEN: Generating message contract since element name kadi from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsimGetir", ReplyAction="*")]
        Disci_Hekim_Program.HekimServis.IsimGetirResponse IsimGetir(Disci_Hekim_Program.HekimServis.IsimGetirRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsimGetir", ReplyAction="*")]
        System.Threading.Tasks.Task<Disci_Hekim_Program.HekimServis.IsimGetirResponse> IsimGetirAsync(Disci_Hekim_Program.HekimServis.IsimGetirRequest request);
        
        // CODEGEN: Generating message contract since element name kadi from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HekimIDGetir", ReplyAction="*")]
        Disci_Hekim_Program.HekimServis.HekimIDGetirResponse HekimIDGetir(Disci_Hekim_Program.HekimServis.HekimIDGetirRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HekimIDGetir", ReplyAction="*")]
        System.Threading.Tasks.Task<Disci_Hekim_Program.HekimServis.HekimIDGetirResponse> HekimIDGetirAsync(Disci_Hekim_Program.HekimServis.HekimIDGetirRequest request);
        
        // CODEGEN: Generating message contract since element name HekimleriGetirResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HekimleriGetir", ReplyAction="*")]
        Disci_Hekim_Program.HekimServis.HekimleriGetirResponse HekimleriGetir(Disci_Hekim_Program.HekimServis.HekimleriGetirRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HekimleriGetir", ReplyAction="*")]
        System.Threading.Tasks.Task<Disci_Hekim_Program.HekimServis.HekimleriGetirResponse> HekimleriGetirAsync(Disci_Hekim_Program.HekimServis.HekimleriGetirRequest request);
        
        // CODEGEN: Generating message contract since element name ad from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/hekimekle", ReplyAction="*")]
        Disci_Hekim_Program.HekimServis.hekimekleResponse hekimekle(Disci_Hekim_Program.HekimServis.hekimekleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/hekimekle", ReplyAction="*")]
        System.Threading.Tasks.Task<Disci_Hekim_Program.HekimServis.hekimekleResponse> hekimekleAsync(Disci_Hekim_Program.HekimServis.hekimekleRequest request);
        
        // CODEGEN: Generating message contract since element name ad from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/hekimguncelle", ReplyAction="*")]
        Disci_Hekim_Program.HekimServis.hekimguncelleResponse hekimguncelle(Disci_Hekim_Program.HekimServis.hekimguncelleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/hekimguncelle", ReplyAction="*")]
        System.Threading.Tasks.Task<Disci_Hekim_Program.HekimServis.hekimguncelleResponse> hekimguncelleAsync(Disci_Hekim_Program.HekimServis.hekimguncelleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/hekimsil", ReplyAction="*")]
        void hekimsil(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/hekimsil", ReplyAction="*")]
        System.Threading.Tasks.Task hekimsilAsync(int id);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IsimGetirRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IsimGetir", Namespace="http://tempuri.org/", Order=0)]
        public Disci_Hekim_Program.HekimServis.IsimGetirRequestBody Body;
        
        public IsimGetirRequest() {
        }
        
        public IsimGetirRequest(Disci_Hekim_Program.HekimServis.IsimGetirRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class IsimGetirRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string kadi;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string sifre;
        
        public IsimGetirRequestBody() {
        }
        
        public IsimGetirRequestBody(string kadi, string sifre) {
            this.kadi = kadi;
            this.sifre = sifre;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IsimGetirResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IsimGetirResponse", Namespace="http://tempuri.org/", Order=0)]
        public Disci_Hekim_Program.HekimServis.IsimGetirResponseBody Body;
        
        public IsimGetirResponse() {
        }
        
        public IsimGetirResponse(Disci_Hekim_Program.HekimServis.IsimGetirResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class IsimGetirResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string IsimGetirResult;
        
        public IsimGetirResponseBody() {
        }
        
        public IsimGetirResponseBody(string IsimGetirResult) {
            this.IsimGetirResult = IsimGetirResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HekimIDGetirRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HekimIDGetir", Namespace="http://tempuri.org/", Order=0)]
        public Disci_Hekim_Program.HekimServis.HekimIDGetirRequestBody Body;
        
        public HekimIDGetirRequest() {
        }
        
        public HekimIDGetirRequest(Disci_Hekim_Program.HekimServis.HekimIDGetirRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HekimIDGetirRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string kadi;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string sifre;
        
        public HekimIDGetirRequestBody() {
        }
        
        public HekimIDGetirRequestBody(string kadi, string sifre) {
            this.kadi = kadi;
            this.sifre = sifre;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HekimIDGetirResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HekimIDGetirResponse", Namespace="http://tempuri.org/", Order=0)]
        public Disci_Hekim_Program.HekimServis.HekimIDGetirResponseBody Body;
        
        public HekimIDGetirResponse() {
        }
        
        public HekimIDGetirResponse(Disci_Hekim_Program.HekimServis.HekimIDGetirResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HekimIDGetirResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int HekimIDGetirResult;
        
        public HekimIDGetirResponseBody() {
        }
        
        public HekimIDGetirResponseBody(int HekimIDGetirResult) {
            this.HekimIDGetirResult = HekimIDGetirResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HekimleriGetirRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HekimleriGetir", Namespace="http://tempuri.org/", Order=0)]
        public Disci_Hekim_Program.HekimServis.HekimleriGetirRequestBody Body;
        
        public HekimleriGetirRequest() {
        }
        
        public HekimleriGetirRequest(Disci_Hekim_Program.HekimServis.HekimleriGetirRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HekimleriGetirRequestBody {
        
        public HekimleriGetirRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HekimleriGetirResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HekimleriGetirResponse", Namespace="http://tempuri.org/", Order=0)]
        public Disci_Hekim_Program.HekimServis.HekimleriGetirResponseBody Body;
        
        public HekimleriGetirResponse() {
        }
        
        public HekimleriGetirResponse(Disci_Hekim_Program.HekimServis.HekimleriGetirResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HekimleriGetirResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Disci_Hekim_Program.HekimServis.HekimListe[] HekimleriGetirResult;
        
        public HekimleriGetirResponseBody() {
        }
        
        public HekimleriGetirResponseBody(Disci_Hekim_Program.HekimServis.HekimListe[] HekimleriGetirResult) {
            this.HekimleriGetirResult = HekimleriGetirResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class hekimekleRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="hekimekle", Namespace="http://tempuri.org/", Order=0)]
        public Disci_Hekim_Program.HekimServis.hekimekleRequestBody Body;
        
        public hekimekleRequest() {
        }
        
        public hekimekleRequest(Disci_Hekim_Program.HekimServis.hekimekleRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class hekimekleRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ad;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string soyad;
        
        public hekimekleRequestBody() {
        }
        
        public hekimekleRequestBody(string ad, string soyad) {
            this.ad = ad;
            this.soyad = soyad;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class hekimekleResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="hekimekleResponse", Namespace="http://tempuri.org/", Order=0)]
        public Disci_Hekim_Program.HekimServis.hekimekleResponseBody Body;
        
        public hekimekleResponse() {
        }
        
        public hekimekleResponse(Disci_Hekim_Program.HekimServis.hekimekleResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class hekimekleResponseBody {
        
        public hekimekleResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class hekimguncelleRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="hekimguncelle", Namespace="http://tempuri.org/", Order=0)]
        public Disci_Hekim_Program.HekimServis.hekimguncelleRequestBody Body;
        
        public hekimguncelleRequest() {
        }
        
        public hekimguncelleRequest(Disci_Hekim_Program.HekimServis.hekimguncelleRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class hekimguncelleRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string ad;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string soyad;
        
        public hekimguncelleRequestBody() {
        }
        
        public hekimguncelleRequestBody(int id, string ad, string soyad) {
            this.id = id;
            this.ad = ad;
            this.soyad = soyad;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class hekimguncelleResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="hekimguncelleResponse", Namespace="http://tempuri.org/", Order=0)]
        public Disci_Hekim_Program.HekimServis.hekimguncelleResponseBody Body;
        
        public hekimguncelleResponse() {
        }
        
        public hekimguncelleResponse(Disci_Hekim_Program.HekimServis.hekimguncelleResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class hekimguncelleResponseBody {
        
        public hekimguncelleResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface HekimSoapChannel : Disci_Hekim_Program.HekimServis.HekimSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HekimSoapClient : System.ServiceModel.ClientBase<Disci_Hekim_Program.HekimServis.HekimSoap>, Disci_Hekim_Program.HekimServis.HekimSoap {
        
        public HekimSoapClient() {
        }
        
        public HekimSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HekimSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HekimSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HekimSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Disci_Hekim_Program.HekimServis.IsimGetirResponse Disci_Hekim_Program.HekimServis.HekimSoap.IsimGetir(Disci_Hekim_Program.HekimServis.IsimGetirRequest request) {
            return base.Channel.IsimGetir(request);
        }
        
        public string IsimGetir(string kadi, string sifre) {
            Disci_Hekim_Program.HekimServis.IsimGetirRequest inValue = new Disci_Hekim_Program.HekimServis.IsimGetirRequest();
            inValue.Body = new Disci_Hekim_Program.HekimServis.IsimGetirRequestBody();
            inValue.Body.kadi = kadi;
            inValue.Body.sifre = sifre;
            Disci_Hekim_Program.HekimServis.IsimGetirResponse retVal = ((Disci_Hekim_Program.HekimServis.HekimSoap)(this)).IsimGetir(inValue);
            return retVal.Body.IsimGetirResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Disci_Hekim_Program.HekimServis.IsimGetirResponse> Disci_Hekim_Program.HekimServis.HekimSoap.IsimGetirAsync(Disci_Hekim_Program.HekimServis.IsimGetirRequest request) {
            return base.Channel.IsimGetirAsync(request);
        }
        
        public System.Threading.Tasks.Task<Disci_Hekim_Program.HekimServis.IsimGetirResponse> IsimGetirAsync(string kadi, string sifre) {
            Disci_Hekim_Program.HekimServis.IsimGetirRequest inValue = new Disci_Hekim_Program.HekimServis.IsimGetirRequest();
            inValue.Body = new Disci_Hekim_Program.HekimServis.IsimGetirRequestBody();
            inValue.Body.kadi = kadi;
            inValue.Body.sifre = sifre;
            return ((Disci_Hekim_Program.HekimServis.HekimSoap)(this)).IsimGetirAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Disci_Hekim_Program.HekimServis.HekimIDGetirResponse Disci_Hekim_Program.HekimServis.HekimSoap.HekimIDGetir(Disci_Hekim_Program.HekimServis.HekimIDGetirRequest request) {
            return base.Channel.HekimIDGetir(request);
        }
        
        public int HekimIDGetir(string kadi, string sifre) {
            Disci_Hekim_Program.HekimServis.HekimIDGetirRequest inValue = new Disci_Hekim_Program.HekimServis.HekimIDGetirRequest();
            inValue.Body = new Disci_Hekim_Program.HekimServis.HekimIDGetirRequestBody();
            inValue.Body.kadi = kadi;
            inValue.Body.sifre = sifre;
            Disci_Hekim_Program.HekimServis.HekimIDGetirResponse retVal = ((Disci_Hekim_Program.HekimServis.HekimSoap)(this)).HekimIDGetir(inValue);
            return retVal.Body.HekimIDGetirResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Disci_Hekim_Program.HekimServis.HekimIDGetirResponse> Disci_Hekim_Program.HekimServis.HekimSoap.HekimIDGetirAsync(Disci_Hekim_Program.HekimServis.HekimIDGetirRequest request) {
            return base.Channel.HekimIDGetirAsync(request);
        }
        
        public System.Threading.Tasks.Task<Disci_Hekim_Program.HekimServis.HekimIDGetirResponse> HekimIDGetirAsync(string kadi, string sifre) {
            Disci_Hekim_Program.HekimServis.HekimIDGetirRequest inValue = new Disci_Hekim_Program.HekimServis.HekimIDGetirRequest();
            inValue.Body = new Disci_Hekim_Program.HekimServis.HekimIDGetirRequestBody();
            inValue.Body.kadi = kadi;
            inValue.Body.sifre = sifre;
            return ((Disci_Hekim_Program.HekimServis.HekimSoap)(this)).HekimIDGetirAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Disci_Hekim_Program.HekimServis.HekimleriGetirResponse Disci_Hekim_Program.HekimServis.HekimSoap.HekimleriGetir(Disci_Hekim_Program.HekimServis.HekimleriGetirRequest request) {
            return base.Channel.HekimleriGetir(request);
        }
        
        public Disci_Hekim_Program.HekimServis.HekimListe[] HekimleriGetir() {
            Disci_Hekim_Program.HekimServis.HekimleriGetirRequest inValue = new Disci_Hekim_Program.HekimServis.HekimleriGetirRequest();
            inValue.Body = new Disci_Hekim_Program.HekimServis.HekimleriGetirRequestBody();
            Disci_Hekim_Program.HekimServis.HekimleriGetirResponse retVal = ((Disci_Hekim_Program.HekimServis.HekimSoap)(this)).HekimleriGetir(inValue);
            return retVal.Body.HekimleriGetirResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Disci_Hekim_Program.HekimServis.HekimleriGetirResponse> Disci_Hekim_Program.HekimServis.HekimSoap.HekimleriGetirAsync(Disci_Hekim_Program.HekimServis.HekimleriGetirRequest request) {
            return base.Channel.HekimleriGetirAsync(request);
        }
        
        public System.Threading.Tasks.Task<Disci_Hekim_Program.HekimServis.HekimleriGetirResponse> HekimleriGetirAsync() {
            Disci_Hekim_Program.HekimServis.HekimleriGetirRequest inValue = new Disci_Hekim_Program.HekimServis.HekimleriGetirRequest();
            inValue.Body = new Disci_Hekim_Program.HekimServis.HekimleriGetirRequestBody();
            return ((Disci_Hekim_Program.HekimServis.HekimSoap)(this)).HekimleriGetirAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Disci_Hekim_Program.HekimServis.hekimekleResponse Disci_Hekim_Program.HekimServis.HekimSoap.hekimekle(Disci_Hekim_Program.HekimServis.hekimekleRequest request) {
            return base.Channel.hekimekle(request);
        }
        
        public void hekimekle(string ad, string soyad) {
            Disci_Hekim_Program.HekimServis.hekimekleRequest inValue = new Disci_Hekim_Program.HekimServis.hekimekleRequest();
            inValue.Body = new Disci_Hekim_Program.HekimServis.hekimekleRequestBody();
            inValue.Body.ad = ad;
            inValue.Body.soyad = soyad;
            Disci_Hekim_Program.HekimServis.hekimekleResponse retVal = ((Disci_Hekim_Program.HekimServis.HekimSoap)(this)).hekimekle(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Disci_Hekim_Program.HekimServis.hekimekleResponse> Disci_Hekim_Program.HekimServis.HekimSoap.hekimekleAsync(Disci_Hekim_Program.HekimServis.hekimekleRequest request) {
            return base.Channel.hekimekleAsync(request);
        }
        
        public System.Threading.Tasks.Task<Disci_Hekim_Program.HekimServis.hekimekleResponse> hekimekleAsync(string ad, string soyad) {
            Disci_Hekim_Program.HekimServis.hekimekleRequest inValue = new Disci_Hekim_Program.HekimServis.hekimekleRequest();
            inValue.Body = new Disci_Hekim_Program.HekimServis.hekimekleRequestBody();
            inValue.Body.ad = ad;
            inValue.Body.soyad = soyad;
            return ((Disci_Hekim_Program.HekimServis.HekimSoap)(this)).hekimekleAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Disci_Hekim_Program.HekimServis.hekimguncelleResponse Disci_Hekim_Program.HekimServis.HekimSoap.hekimguncelle(Disci_Hekim_Program.HekimServis.hekimguncelleRequest request) {
            return base.Channel.hekimguncelle(request);
        }
        
        public void hekimguncelle(int id, string ad, string soyad) {
            Disci_Hekim_Program.HekimServis.hekimguncelleRequest inValue = new Disci_Hekim_Program.HekimServis.hekimguncelleRequest();
            inValue.Body = new Disci_Hekim_Program.HekimServis.hekimguncelleRequestBody();
            inValue.Body.id = id;
            inValue.Body.ad = ad;
            inValue.Body.soyad = soyad;
            Disci_Hekim_Program.HekimServis.hekimguncelleResponse retVal = ((Disci_Hekim_Program.HekimServis.HekimSoap)(this)).hekimguncelle(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Disci_Hekim_Program.HekimServis.hekimguncelleResponse> Disci_Hekim_Program.HekimServis.HekimSoap.hekimguncelleAsync(Disci_Hekim_Program.HekimServis.hekimguncelleRequest request) {
            return base.Channel.hekimguncelleAsync(request);
        }
        
        public System.Threading.Tasks.Task<Disci_Hekim_Program.HekimServis.hekimguncelleResponse> hekimguncelleAsync(int id, string ad, string soyad) {
            Disci_Hekim_Program.HekimServis.hekimguncelleRequest inValue = new Disci_Hekim_Program.HekimServis.hekimguncelleRequest();
            inValue.Body = new Disci_Hekim_Program.HekimServis.hekimguncelleRequestBody();
            inValue.Body.id = id;
            inValue.Body.ad = ad;
            inValue.Body.soyad = soyad;
            return ((Disci_Hekim_Program.HekimServis.HekimSoap)(this)).hekimguncelleAsync(inValue);
        }
        
        public void hekimsil(int id) {
            base.Channel.hekimsil(id);
        }
        
        public System.Threading.Tasks.Task hekimsilAsync(int id) {
            return base.Channel.hekimsilAsync(id);
        }
    }
}
