//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Disci_Hekim_Program.RandevuServis {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Randevu", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Randevu : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int RandevuIDField;
        
        private System.Nullable<int> HastaIDField;
        
        private System.Nullable<int> HekimIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HastaAdiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HastaSoyadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TCField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RandevuTarihField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RandevuSaatField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int RandevuID {
            get {
                return this.RandevuIDField;
            }
            set {
                if ((this.RandevuIDField.Equals(value) != true)) {
                    this.RandevuIDField = value;
                    this.RaisePropertyChanged("RandevuID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public System.Nullable<int> HastaID {
            get {
                return this.HastaIDField;
            }
            set {
                if ((this.HastaIDField.Equals(value) != true)) {
                    this.HastaIDField = value;
                    this.RaisePropertyChanged("HastaID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public System.Nullable<int> HekimID {
            get {
                return this.HekimIDField;
            }
            set {
                if ((this.HekimIDField.Equals(value) != true)) {
                    this.HekimIDField = value;
                    this.RaisePropertyChanged("HekimID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string HastaAdi {
            get {
                return this.HastaAdiField;
            }
            set {
                if ((object.ReferenceEquals(this.HastaAdiField, value) != true)) {
                    this.HastaAdiField = value;
                    this.RaisePropertyChanged("HastaAdi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string HastaSoyad {
            get {
                return this.HastaSoyadField;
            }
            set {
                if ((object.ReferenceEquals(this.HastaSoyadField, value) != true)) {
                    this.HastaSoyadField = value;
                    this.RaisePropertyChanged("HastaSoyad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string TC {
            get {
                return this.TCField;
            }
            set {
                if ((object.ReferenceEquals(this.TCField, value) != true)) {
                    this.TCField = value;
                    this.RaisePropertyChanged("TC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string RandevuTarih {
            get {
                return this.RandevuTarihField;
            }
            set {
                if ((object.ReferenceEquals(this.RandevuTarihField, value) != true)) {
                    this.RandevuTarihField = value;
                    this.RaisePropertyChanged("RandevuTarih");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string RandevuSaat {
            get {
                return this.RandevuSaatField;
            }
            set {
                if ((object.ReferenceEquals(this.RandevuSaatField, value) != true)) {
                    this.RandevuSaatField = value;
                    this.RaisePropertyChanged("RandevuSaat");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RandevuServis.RandevuIslemleriSoap")]
    public interface RandevuIslemleriSoap {
        
        // CODEGEN: Generating message contract since element name RandevuListeleResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RandevuListele", ReplyAction="*")]
        Disci_Hekim_Program.RandevuServis.RandevuListeleResponse RandevuListele(Disci_Hekim_Program.RandevuServis.RandevuListeleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RandevuListele", ReplyAction="*")]
        System.Threading.Tasks.Task<Disci_Hekim_Program.RandevuServis.RandevuListeleResponse> RandevuListeleAsync(Disci_Hekim_Program.RandevuServis.RandevuListeleRequest request);
        
        // CODEGEN: Generating message contract since element name TC from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/KisiGetir", ReplyAction="*")]
        Disci_Hekim_Program.RandevuServis.KisiGetirResponse KisiGetir(Disci_Hekim_Program.RandevuServis.KisiGetirRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/KisiGetir", ReplyAction="*")]
        System.Threading.Tasks.Task<Disci_Hekim_Program.RandevuServis.KisiGetirResponse> KisiGetirAsync(Disci_Hekim_Program.RandevuServis.KisiGetirRequest request);
        
        // CODEGEN: Generating message contract since element name tarih from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RandevuEkle", ReplyAction="*")]
        Disci_Hekim_Program.RandevuServis.RandevuEkleResponse RandevuEkle(Disci_Hekim_Program.RandevuServis.RandevuEkleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RandevuEkle", ReplyAction="*")]
        System.Threading.Tasks.Task<Disci_Hekim_Program.RandevuServis.RandevuEkleResponse> RandevuEkleAsync(Disci_Hekim_Program.RandevuServis.RandevuEkleRequest request);
        
        // CODEGEN: Generating message contract since element name tarih from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RandevuFiltrele", ReplyAction="*")]
        Disci_Hekim_Program.RandevuServis.RandevuFiltreleResponse RandevuFiltrele(Disci_Hekim_Program.RandevuServis.RandevuFiltreleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RandevuFiltrele", ReplyAction="*")]
        System.Threading.Tasks.Task<Disci_Hekim_Program.RandevuServis.RandevuFiltreleResponse> RandevuFiltreleAsync(Disci_Hekim_Program.RandevuServis.RandevuFiltreleRequest request);
        
        // CODEGEN: Generating message contract since element name randevutarih from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RandevuGuncelle", ReplyAction="*")]
        Disci_Hekim_Program.RandevuServis.RandevuGuncelleResponse RandevuGuncelle(Disci_Hekim_Program.RandevuServis.RandevuGuncelleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RandevuGuncelle", ReplyAction="*")]
        System.Threading.Tasks.Task<Disci_Hekim_Program.RandevuServis.RandevuGuncelleResponse> RandevuGuncelleAsync(Disci_Hekim_Program.RandevuServis.RandevuGuncelleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RandevuSil", ReplyAction="*")]
        void RandevuSil(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RandevuSil", ReplyAction="*")]
        System.Threading.Tasks.Task RandevuSilAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/hekimata", ReplyAction="*")]
        void hekimata(int randid, int hekimid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/hekimata", ReplyAction="*")]
        System.Threading.Tasks.Task hekimataAsync(int randid, int hekimid);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RandevuListeleRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RandevuListele", Namespace="http://tempuri.org/", Order=0)]
        public Disci_Hekim_Program.RandevuServis.RandevuListeleRequestBody Body;
        
        public RandevuListeleRequest() {
        }
        
        public RandevuListeleRequest(Disci_Hekim_Program.RandevuServis.RandevuListeleRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class RandevuListeleRequestBody {
        
        public RandevuListeleRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RandevuListeleResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RandevuListeleResponse", Namespace="http://tempuri.org/", Order=0)]
        public Disci_Hekim_Program.RandevuServis.RandevuListeleResponseBody Body;
        
        public RandevuListeleResponse() {
        }
        
        public RandevuListeleResponse(Disci_Hekim_Program.RandevuServis.RandevuListeleResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RandevuListeleResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Disci_Hekim_Program.RandevuServis.Randevu[] RandevuListeleResult;
        
        public RandevuListeleResponseBody() {
        }
        
        public RandevuListeleResponseBody(Disci_Hekim_Program.RandevuServis.Randevu[] RandevuListeleResult) {
            this.RandevuListeleResult = RandevuListeleResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class KisiGetirRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="KisiGetir", Namespace="http://tempuri.org/", Order=0)]
        public Disci_Hekim_Program.RandevuServis.KisiGetirRequestBody Body;
        
        public KisiGetirRequest() {
        }
        
        public KisiGetirRequest(Disci_Hekim_Program.RandevuServis.KisiGetirRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class KisiGetirRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string TC;
        
        public KisiGetirRequestBody() {
        }
        
        public KisiGetirRequestBody(string TC) {
            this.TC = TC;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class KisiGetirResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="KisiGetirResponse", Namespace="http://tempuri.org/", Order=0)]
        public Disci_Hekim_Program.RandevuServis.KisiGetirResponseBody Body;
        
        public KisiGetirResponse() {
        }
        
        public KisiGetirResponse(Disci_Hekim_Program.RandevuServis.KisiGetirResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class KisiGetirResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Disci_Hekim_Program.RandevuServis.Randevu[] KisiGetirResult;
        
        public KisiGetirResponseBody() {
        }
        
        public KisiGetirResponseBody(Disci_Hekim_Program.RandevuServis.Randevu[] KisiGetirResult) {
            this.KisiGetirResult = KisiGetirResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RandevuEkleRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RandevuEkle", Namespace="http://tempuri.org/", Order=0)]
        public Disci_Hekim_Program.RandevuServis.RandevuEkleRequestBody Body;
        
        public RandevuEkleRequest() {
        }
        
        public RandevuEkleRequest(Disci_Hekim_Program.RandevuServis.RandevuEkleRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RandevuEkleRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int hastaid;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int hekimid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string tarih;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string saat;
        
        public RandevuEkleRequestBody() {
        }
        
        public RandevuEkleRequestBody(int hastaid, int hekimid, string tarih, string saat) {
            this.hastaid = hastaid;
            this.hekimid = hekimid;
            this.tarih = tarih;
            this.saat = saat;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RandevuEkleResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RandevuEkleResponse", Namespace="http://tempuri.org/", Order=0)]
        public Disci_Hekim_Program.RandevuServis.RandevuEkleResponseBody Body;
        
        public RandevuEkleResponse() {
        }
        
        public RandevuEkleResponse(Disci_Hekim_Program.RandevuServis.RandevuEkleResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class RandevuEkleResponseBody {
        
        public RandevuEkleResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RandevuFiltreleRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RandevuFiltrele", Namespace="http://tempuri.org/", Order=0)]
        public Disci_Hekim_Program.RandevuServis.RandevuFiltreleRequestBody Body;
        
        public RandevuFiltreleRequest() {
        }
        
        public RandevuFiltreleRequest(Disci_Hekim_Program.RandevuServis.RandevuFiltreleRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RandevuFiltreleRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string tarih;
        
        public RandevuFiltreleRequestBody() {
        }
        
        public RandevuFiltreleRequestBody(string tarih) {
            this.tarih = tarih;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RandevuFiltreleResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RandevuFiltreleResponse", Namespace="http://tempuri.org/", Order=0)]
        public Disci_Hekim_Program.RandevuServis.RandevuFiltreleResponseBody Body;
        
        public RandevuFiltreleResponse() {
        }
        
        public RandevuFiltreleResponse(Disci_Hekim_Program.RandevuServis.RandevuFiltreleResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RandevuFiltreleResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Disci_Hekim_Program.RandevuServis.Randevu[] RandevuFiltreleResult;
        
        public RandevuFiltreleResponseBody() {
        }
        
        public RandevuFiltreleResponseBody(Disci_Hekim_Program.RandevuServis.Randevu[] RandevuFiltreleResult) {
            this.RandevuFiltreleResult = RandevuFiltreleResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RandevuGuncelleRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RandevuGuncelle", Namespace="http://tempuri.org/", Order=0)]
        public Disci_Hekim_Program.RandevuServis.RandevuGuncelleRequestBody Body;
        
        public RandevuGuncelleRequest() {
        }
        
        public RandevuGuncelleRequest(Disci_Hekim_Program.RandevuServis.RandevuGuncelleRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RandevuGuncelleRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int hastaid;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int hekimid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string randevutarih;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string randevusaat;
        
        public RandevuGuncelleRequestBody() {
        }
        
        public RandevuGuncelleRequestBody(int id, int hastaid, int hekimid, string randevutarih, string randevusaat) {
            this.id = id;
            this.hastaid = hastaid;
            this.hekimid = hekimid;
            this.randevutarih = randevutarih;
            this.randevusaat = randevusaat;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RandevuGuncelleResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RandevuGuncelleResponse", Namespace="http://tempuri.org/", Order=0)]
        public Disci_Hekim_Program.RandevuServis.RandevuGuncelleResponseBody Body;
        
        public RandevuGuncelleResponse() {
        }
        
        public RandevuGuncelleResponse(Disci_Hekim_Program.RandevuServis.RandevuGuncelleResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class RandevuGuncelleResponseBody {
        
        public RandevuGuncelleResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface RandevuIslemleriSoapChannel : Disci_Hekim_Program.RandevuServis.RandevuIslemleriSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RandevuIslemleriSoapClient : System.ServiceModel.ClientBase<Disci_Hekim_Program.RandevuServis.RandevuIslemleriSoap>, Disci_Hekim_Program.RandevuServis.RandevuIslemleriSoap {
        
        public RandevuIslemleriSoapClient() {
        }
        
        public RandevuIslemleriSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RandevuIslemleriSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RandevuIslemleriSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RandevuIslemleriSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Disci_Hekim_Program.RandevuServis.RandevuListeleResponse Disci_Hekim_Program.RandevuServis.RandevuIslemleriSoap.RandevuListele(Disci_Hekim_Program.RandevuServis.RandevuListeleRequest request) {
            return base.Channel.RandevuListele(request);
        }
        
        public Disci_Hekim_Program.RandevuServis.Randevu[] RandevuListele() {
            Disci_Hekim_Program.RandevuServis.RandevuListeleRequest inValue = new Disci_Hekim_Program.RandevuServis.RandevuListeleRequest();
            inValue.Body = new Disci_Hekim_Program.RandevuServis.RandevuListeleRequestBody();
            Disci_Hekim_Program.RandevuServis.RandevuListeleResponse retVal = ((Disci_Hekim_Program.RandevuServis.RandevuIslemleriSoap)(this)).RandevuListele(inValue);
            return retVal.Body.RandevuListeleResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Disci_Hekim_Program.RandevuServis.RandevuListeleResponse> Disci_Hekim_Program.RandevuServis.RandevuIslemleriSoap.RandevuListeleAsync(Disci_Hekim_Program.RandevuServis.RandevuListeleRequest request) {
            return base.Channel.RandevuListeleAsync(request);
        }
        
        public System.Threading.Tasks.Task<Disci_Hekim_Program.RandevuServis.RandevuListeleResponse> RandevuListeleAsync() {
            Disci_Hekim_Program.RandevuServis.RandevuListeleRequest inValue = new Disci_Hekim_Program.RandevuServis.RandevuListeleRequest();
            inValue.Body = new Disci_Hekim_Program.RandevuServis.RandevuListeleRequestBody();
            return ((Disci_Hekim_Program.RandevuServis.RandevuIslemleriSoap)(this)).RandevuListeleAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Disci_Hekim_Program.RandevuServis.KisiGetirResponse Disci_Hekim_Program.RandevuServis.RandevuIslemleriSoap.KisiGetir(Disci_Hekim_Program.RandevuServis.KisiGetirRequest request) {
            return base.Channel.KisiGetir(request);
        }
        
        public Disci_Hekim_Program.RandevuServis.Randevu[] KisiGetir(string TC) {
            Disci_Hekim_Program.RandevuServis.KisiGetirRequest inValue = new Disci_Hekim_Program.RandevuServis.KisiGetirRequest();
            inValue.Body = new Disci_Hekim_Program.RandevuServis.KisiGetirRequestBody();
            inValue.Body.TC = TC;
            Disci_Hekim_Program.RandevuServis.KisiGetirResponse retVal = ((Disci_Hekim_Program.RandevuServis.RandevuIslemleriSoap)(this)).KisiGetir(inValue);
            return retVal.Body.KisiGetirResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Disci_Hekim_Program.RandevuServis.KisiGetirResponse> Disci_Hekim_Program.RandevuServis.RandevuIslemleriSoap.KisiGetirAsync(Disci_Hekim_Program.RandevuServis.KisiGetirRequest request) {
            return base.Channel.KisiGetirAsync(request);
        }
        
        public System.Threading.Tasks.Task<Disci_Hekim_Program.RandevuServis.KisiGetirResponse> KisiGetirAsync(string TC) {
            Disci_Hekim_Program.RandevuServis.KisiGetirRequest inValue = new Disci_Hekim_Program.RandevuServis.KisiGetirRequest();
            inValue.Body = new Disci_Hekim_Program.RandevuServis.KisiGetirRequestBody();
            inValue.Body.TC = TC;
            return ((Disci_Hekim_Program.RandevuServis.RandevuIslemleriSoap)(this)).KisiGetirAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Disci_Hekim_Program.RandevuServis.RandevuEkleResponse Disci_Hekim_Program.RandevuServis.RandevuIslemleriSoap.RandevuEkle(Disci_Hekim_Program.RandevuServis.RandevuEkleRequest request) {
            return base.Channel.RandevuEkle(request);
        }
        
        public void RandevuEkle(int hastaid, int hekimid, string tarih, string saat) {
            Disci_Hekim_Program.RandevuServis.RandevuEkleRequest inValue = new Disci_Hekim_Program.RandevuServis.RandevuEkleRequest();
            inValue.Body = new Disci_Hekim_Program.RandevuServis.RandevuEkleRequestBody();
            inValue.Body.hastaid = hastaid;
            inValue.Body.hekimid = hekimid;
            inValue.Body.tarih = tarih;
            inValue.Body.saat = saat;
            Disci_Hekim_Program.RandevuServis.RandevuEkleResponse retVal = ((Disci_Hekim_Program.RandevuServis.RandevuIslemleriSoap)(this)).RandevuEkle(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Disci_Hekim_Program.RandevuServis.RandevuEkleResponse> Disci_Hekim_Program.RandevuServis.RandevuIslemleriSoap.RandevuEkleAsync(Disci_Hekim_Program.RandevuServis.RandevuEkleRequest request) {
            return base.Channel.RandevuEkleAsync(request);
        }
        
        public System.Threading.Tasks.Task<Disci_Hekim_Program.RandevuServis.RandevuEkleResponse> RandevuEkleAsync(int hastaid, int hekimid, string tarih, string saat) {
            Disci_Hekim_Program.RandevuServis.RandevuEkleRequest inValue = new Disci_Hekim_Program.RandevuServis.RandevuEkleRequest();
            inValue.Body = new Disci_Hekim_Program.RandevuServis.RandevuEkleRequestBody();
            inValue.Body.hastaid = hastaid;
            inValue.Body.hekimid = hekimid;
            inValue.Body.tarih = tarih;
            inValue.Body.saat = saat;
            return ((Disci_Hekim_Program.RandevuServis.RandevuIslemleriSoap)(this)).RandevuEkleAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Disci_Hekim_Program.RandevuServis.RandevuFiltreleResponse Disci_Hekim_Program.RandevuServis.RandevuIslemleriSoap.RandevuFiltrele(Disci_Hekim_Program.RandevuServis.RandevuFiltreleRequest request) {
            return base.Channel.RandevuFiltrele(request);
        }
        
        public Disci_Hekim_Program.RandevuServis.Randevu[] RandevuFiltrele(string tarih) {
            Disci_Hekim_Program.RandevuServis.RandevuFiltreleRequest inValue = new Disci_Hekim_Program.RandevuServis.RandevuFiltreleRequest();
            inValue.Body = new Disci_Hekim_Program.RandevuServis.RandevuFiltreleRequestBody();
            inValue.Body.tarih = tarih;
            Disci_Hekim_Program.RandevuServis.RandevuFiltreleResponse retVal = ((Disci_Hekim_Program.RandevuServis.RandevuIslemleriSoap)(this)).RandevuFiltrele(inValue);
            return retVal.Body.RandevuFiltreleResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Disci_Hekim_Program.RandevuServis.RandevuFiltreleResponse> Disci_Hekim_Program.RandevuServis.RandevuIslemleriSoap.RandevuFiltreleAsync(Disci_Hekim_Program.RandevuServis.RandevuFiltreleRequest request) {
            return base.Channel.RandevuFiltreleAsync(request);
        }
        
        public System.Threading.Tasks.Task<Disci_Hekim_Program.RandevuServis.RandevuFiltreleResponse> RandevuFiltreleAsync(string tarih) {
            Disci_Hekim_Program.RandevuServis.RandevuFiltreleRequest inValue = new Disci_Hekim_Program.RandevuServis.RandevuFiltreleRequest();
            inValue.Body = new Disci_Hekim_Program.RandevuServis.RandevuFiltreleRequestBody();
            inValue.Body.tarih = tarih;
            return ((Disci_Hekim_Program.RandevuServis.RandevuIslemleriSoap)(this)).RandevuFiltreleAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Disci_Hekim_Program.RandevuServis.RandevuGuncelleResponse Disci_Hekim_Program.RandevuServis.RandevuIslemleriSoap.RandevuGuncelle(Disci_Hekim_Program.RandevuServis.RandevuGuncelleRequest request) {
            return base.Channel.RandevuGuncelle(request);
        }
        
        public void RandevuGuncelle(int id, int hastaid, int hekimid, string randevutarih, string randevusaat) {
            Disci_Hekim_Program.RandevuServis.RandevuGuncelleRequest inValue = new Disci_Hekim_Program.RandevuServis.RandevuGuncelleRequest();
            inValue.Body = new Disci_Hekim_Program.RandevuServis.RandevuGuncelleRequestBody();
            inValue.Body.id = id;
            inValue.Body.hastaid = hastaid;
            inValue.Body.hekimid = hekimid;
            inValue.Body.randevutarih = randevutarih;
            inValue.Body.randevusaat = randevusaat;
            Disci_Hekim_Program.RandevuServis.RandevuGuncelleResponse retVal = ((Disci_Hekim_Program.RandevuServis.RandevuIslemleriSoap)(this)).RandevuGuncelle(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Disci_Hekim_Program.RandevuServis.RandevuGuncelleResponse> Disci_Hekim_Program.RandevuServis.RandevuIslemleriSoap.RandevuGuncelleAsync(Disci_Hekim_Program.RandevuServis.RandevuGuncelleRequest request) {
            return base.Channel.RandevuGuncelleAsync(request);
        }
        
        public System.Threading.Tasks.Task<Disci_Hekim_Program.RandevuServis.RandevuGuncelleResponse> RandevuGuncelleAsync(int id, int hastaid, int hekimid, string randevutarih, string randevusaat) {
            Disci_Hekim_Program.RandevuServis.RandevuGuncelleRequest inValue = new Disci_Hekim_Program.RandevuServis.RandevuGuncelleRequest();
            inValue.Body = new Disci_Hekim_Program.RandevuServis.RandevuGuncelleRequestBody();
            inValue.Body.id = id;
            inValue.Body.hastaid = hastaid;
            inValue.Body.hekimid = hekimid;
            inValue.Body.randevutarih = randevutarih;
            inValue.Body.randevusaat = randevusaat;
            return ((Disci_Hekim_Program.RandevuServis.RandevuIslemleriSoap)(this)).RandevuGuncelleAsync(inValue);
        }
        
        public void RandevuSil(int id) {
            base.Channel.RandevuSil(id);
        }
        
        public System.Threading.Tasks.Task RandevuSilAsync(int id) {
            return base.Channel.RandevuSilAsync(id);
        }
        
        public void hekimata(int randid, int hekimid) {
            base.Channel.hekimata(randid, hekimid);
        }
        
        public System.Threading.Tasks.Task hekimataAsync(int randid, int hekimid) {
            return base.Channel.hekimataAsync(randid, hekimid);
        }
    }
}
