//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Disci_Hekim_Program.HastaServis {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Hastalar", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Hastalar : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int HastaIDField;
        
        private System.Nullable<int> HekimIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HastaAdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HastaSoyadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TCField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DurumField;
        
        private System.Nullable<int> YasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CinsiyetField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int HastaID {
            get {
                return this.HastaIDField;
            }
            set {
                if ((this.HastaIDField.Equals(value) != true)) {
                    this.HastaIDField = value;
                    this.RaisePropertyChanged("HastaID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<int> HekimID {
            get {
                return this.HekimIDField;
            }
            set {
                if ((this.HekimIDField.Equals(value) != true)) {
                    this.HekimIDField = value;
                    this.RaisePropertyChanged("HekimID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string HastaAd {
            get {
                return this.HastaAdField;
            }
            set {
                if ((object.ReferenceEquals(this.HastaAdField, value) != true)) {
                    this.HastaAdField = value;
                    this.RaisePropertyChanged("HastaAd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string HastaSoyad {
            get {
                return this.HastaSoyadField;
            }
            set {
                if ((object.ReferenceEquals(this.HastaSoyadField, value) != true)) {
                    this.HastaSoyadField = value;
                    this.RaisePropertyChanged("HastaSoyad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string TC {
            get {
                return this.TCField;
            }
            set {
                if ((object.ReferenceEquals(this.TCField, value) != true)) {
                    this.TCField = value;
                    this.RaisePropertyChanged("TC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Tel {
            get {
                return this.TelField;
            }
            set {
                if ((object.ReferenceEquals(this.TelField, value) != true)) {
                    this.TelField = value;
                    this.RaisePropertyChanged("Tel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Mail {
            get {
                return this.MailField;
            }
            set {
                if ((object.ReferenceEquals(this.MailField, value) != true)) {
                    this.MailField = value;
                    this.RaisePropertyChanged("Mail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string Durum {
            get {
                return this.DurumField;
            }
            set {
                if ((object.ReferenceEquals(this.DurumField, value) != true)) {
                    this.DurumField = value;
                    this.RaisePropertyChanged("Durum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public System.Nullable<int> Yas {
            get {
                return this.YasField;
            }
            set {
                if ((this.YasField.Equals(value) != true)) {
                    this.YasField = value;
                    this.RaisePropertyChanged("Yas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string Cinsiyet {
            get {
                return this.CinsiyetField;
            }
            set {
                if ((object.ReferenceEquals(this.CinsiyetField, value) != true)) {
                    this.CinsiyetField = value;
                    this.RaisePropertyChanged("Cinsiyet");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="HastaServis.HastaSoap")]
    public interface HastaSoap {
        
        // CODEGEN: Generating message contract since element name IsimGetirResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsimGetir", ReplyAction="*")]
        Disci_Hekim_Program.HastaServis.IsimGetirResponse IsimGetir(Disci_Hekim_Program.HastaServis.IsimGetirRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsimGetir", ReplyAction="*")]
        System.Threading.Tasks.Task<Disci_Hekim_Program.HastaServis.IsimGetirResponse> IsimGetirAsync(Disci_Hekim_Program.HastaServis.IsimGetirRequest request);
        
        // CODEGEN: Generating message contract since element name SoyadResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Soyad", ReplyAction="*")]
        Disci_Hekim_Program.HastaServis.SoyadResponse Soyad(Disci_Hekim_Program.HastaServis.SoyadRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Soyad", ReplyAction="*")]
        System.Threading.Tasks.Task<Disci_Hekim_Program.HastaServis.SoyadResponse> SoyadAsync(Disci_Hekim_Program.HastaServis.SoyadRequest request);
        
        // CODEGEN: Generating message contract since element name TCGetirResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TCGetir", ReplyAction="*")]
        Disci_Hekim_Program.HastaServis.TCGetirResponse TCGetir(Disci_Hekim_Program.HastaServis.TCGetirRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TCGetir", ReplyAction="*")]
        System.Threading.Tasks.Task<Disci_Hekim_Program.HastaServis.TCGetirResponse> TCGetirAsync(Disci_Hekim_Program.HastaServis.TCGetirRequest request);
        
        // CODEGEN: Generating message contract since element name TelGetirResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TelGetir", ReplyAction="*")]
        Disci_Hekim_Program.HastaServis.TelGetirResponse TelGetir(Disci_Hekim_Program.HastaServis.TelGetirRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TelGetir", ReplyAction="*")]
        System.Threading.Tasks.Task<Disci_Hekim_Program.HastaServis.TelGetirResponse> TelGetirAsync(Disci_Hekim_Program.HastaServis.TelGetirRequest request);
        
        // CODEGEN: Generating message contract since element name MailGetirResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MailGetir", ReplyAction="*")]
        Disci_Hekim_Program.HastaServis.MailGetirResponse MailGetir(Disci_Hekim_Program.HastaServis.MailGetirRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MailGetir", ReplyAction="*")]
        System.Threading.Tasks.Task<Disci_Hekim_Program.HastaServis.MailGetirResponse> MailGetirAsync(Disci_Hekim_Program.HastaServis.MailGetirRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/YasGetir", ReplyAction="*")]
        int YasGetir(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/YasGetir", ReplyAction="*")]
        System.Threading.Tasks.Task<int> YasGetirAsync(int id);
        
        // CODEGEN: Generating message contract since element name CinsyetGetirResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CinsyetGetir", ReplyAction="*")]
        Disci_Hekim_Program.HastaServis.CinsyetGetirResponse CinsyetGetir(Disci_Hekim_Program.HastaServis.CinsyetGetirRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CinsyetGetir", ReplyAction="*")]
        System.Threading.Tasks.Task<Disci_Hekim_Program.HastaServis.CinsyetGetirResponse> CinsyetGetirAsync(Disci_Hekim_Program.HastaServis.CinsyetGetirRequest request);
        
        // CODEGEN: Generating message contract since element name TC from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDGetir", ReplyAction="*")]
        Disci_Hekim_Program.HastaServis.IDGetirResponse IDGetir(Disci_Hekim_Program.HastaServis.IDGetirRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDGetir", ReplyAction="*")]
        System.Threading.Tasks.Task<Disci_Hekim_Program.HastaServis.IDGetirResponse> IDGetirAsync(Disci_Hekim_Program.HastaServis.IDGetirRequest request);
        
        // CODEGEN: Generating message contract since element name durum from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DurumGuncelle", ReplyAction="*")]
        Disci_Hekim_Program.HastaServis.DurumGuncelleResponse DurumGuncelle(Disci_Hekim_Program.HastaServis.DurumGuncelleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DurumGuncelle", ReplyAction="*")]
        System.Threading.Tasks.Task<Disci_Hekim_Program.HastaServis.DurumGuncelleResponse> DurumGuncelleAsync(Disci_Hekim_Program.HastaServis.DurumGuncelleRequest request);
        
        // CODEGEN: Generating message contract since element name IsimGetirResepsiyonResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsimGetirResepsiyon", ReplyAction="*")]
        Disci_Hekim_Program.HastaServis.IsimGetirResepsiyonResponse IsimGetirResepsiyon(Disci_Hekim_Program.HastaServis.IsimGetirResepsiyonRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsimGetirResepsiyon", ReplyAction="*")]
        System.Threading.Tasks.Task<Disci_Hekim_Program.HastaServis.IsimGetirResepsiyonResponse> IsimGetirResepsiyonAsync(Disci_Hekim_Program.HastaServis.IsimGetirResepsiyonRequest request);
        
        // CODEGEN: Generating message contract since element name SoyadGetirResepsiyonResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SoyadGetirResepsiyon", ReplyAction="*")]
        Disci_Hekim_Program.HastaServis.SoyadGetirResepsiyonResponse SoyadGetirResepsiyon(Disci_Hekim_Program.HastaServis.SoyadGetirResepsiyonRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SoyadGetirResepsiyon", ReplyAction="*")]
        System.Threading.Tasks.Task<Disci_Hekim_Program.HastaServis.SoyadGetirResepsiyonResponse> SoyadGetirResepsiyonAsync(Disci_Hekim_Program.HastaServis.SoyadGetirResepsiyonRequest request);
        
        // CODEGEN: Generating message contract since element name TCGetirResepsiyonResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TCGetirResepsiyon", ReplyAction="*")]
        Disci_Hekim_Program.HastaServis.TCGetirResepsiyonResponse TCGetirResepsiyon(Disci_Hekim_Program.HastaServis.TCGetirResepsiyonRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TCGetirResepsiyon", ReplyAction="*")]
        System.Threading.Tasks.Task<Disci_Hekim_Program.HastaServis.TCGetirResepsiyonResponse> TCGetirResepsiyonAsync(Disci_Hekim_Program.HastaServis.TCGetirResepsiyonRequest request);
        
        // CODEGEN: Generating message contract since element name HastaListeleResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HastaListele", ReplyAction="*")]
        Disci_Hekim_Program.HastaServis.HastaListeleResponse HastaListele(Disci_Hekim_Program.HastaServis.HastaListeleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HastaListele", ReplyAction="*")]
        System.Threading.Tasks.Task<Disci_Hekim_Program.HastaServis.HastaListeleResponse> HastaListeleAsync(Disci_Hekim_Program.HastaServis.HastaListeleRequest request);
        
        // CODEGEN: Generating message contract since element name tc from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HastaListeleTCGore", ReplyAction="*")]
        Disci_Hekim_Program.HastaServis.HastaListeleTCGoreResponse HastaListeleTCGore(Disci_Hekim_Program.HastaServis.HastaListeleTCGoreRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HastaListeleTCGore", ReplyAction="*")]
        System.Threading.Tasks.Task<Disci_Hekim_Program.HastaServis.HastaListeleTCGoreResponse> HastaListeleTCGoreAsync(Disci_Hekim_Program.HastaServis.HastaListeleTCGoreRequest request);
        
        // CODEGEN: Generating message contract since element name hastad from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HastaEkle", ReplyAction="*")]
        Disci_Hekim_Program.HastaServis.HastaEkleResponse HastaEkle(Disci_Hekim_Program.HastaServis.HastaEkleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HastaEkle", ReplyAction="*")]
        System.Threading.Tasks.Task<Disci_Hekim_Program.HastaServis.HastaEkleResponse> HastaEkleAsync(Disci_Hekim_Program.HastaServis.HastaEkleRequest request);
        
        // CODEGEN: Generating message contract since element name hastad from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HastaGuncelle", ReplyAction="*")]
        Disci_Hekim_Program.HastaServis.HastaGuncelleResponse HastaGuncelle(Disci_Hekim_Program.HastaServis.HastaGuncelleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HastaGuncelle", ReplyAction="*")]
        System.Threading.Tasks.Task<Disci_Hekim_Program.HastaServis.HastaGuncelleResponse> HastaGuncelleAsync(Disci_Hekim_Program.HastaServis.HastaGuncelleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/hastasil", ReplyAction="*")]
        void hastasil(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/hastasil", ReplyAction="*")]
        System.Threading.Tasks.Task hastasilAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/hekimegonder", ReplyAction="*")]
        void hekimegonder(int id, int hekimid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/hekimegonder", ReplyAction="*")]
        System.Threading.Tasks.Task hekimegonderAsync(int id, int hekimid);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IsimGetirRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IsimGetir", Namespace="http://tempuri.org/", Order=0)]
        public Disci_Hekim_Program.HastaServis.IsimGetirRequestBody Body;
        
        public IsimGetirRequest() {
        }
        
        public IsimGetirRequest(Disci_Hekim_Program.HastaServis.IsimGetirRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class IsimGetirRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public IsimGetirRequestBody() {
        }
        
        public IsimGetirRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IsimGetirResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IsimGetirResponse", Namespace="http://tempuri.org/", Order=0)]
        public Disci_Hekim_Program.HastaServis.IsimGetirResponseBody Body;
        
        public IsimGetirResponse() {
        }
        
        public IsimGetirResponse(Disci_Hekim_Program.HastaServis.IsimGetirResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class IsimGetirResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string IsimGetirResult;
        
        public IsimGetirResponseBody() {
        }
        
        public IsimGetirResponseBody(string IsimGetirResult) {
            this.IsimGetirResult = IsimGetirResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SoyadRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Soyad", Namespace="http://tempuri.org/", Order=0)]
        public Disci_Hekim_Program.HastaServis.SoyadRequestBody Body;
        
        public SoyadRequest() {
        }
        
        public SoyadRequest(Disci_Hekim_Program.HastaServis.SoyadRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SoyadRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public SoyadRequestBody() {
        }
        
        public SoyadRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SoyadResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SoyadResponse", Namespace="http://tempuri.org/", Order=0)]
        public Disci_Hekim_Program.HastaServis.SoyadResponseBody Body;
        
        public SoyadResponse() {
        }
        
        public SoyadResponse(Disci_Hekim_Program.HastaServis.SoyadResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SoyadResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SoyadResult;
        
        public SoyadResponseBody() {
        }
        
        public SoyadResponseBody(string SoyadResult) {
            this.SoyadResult = SoyadResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TCGetirRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TCGetir", Namespace="http://tempuri.org/", Order=0)]
        public Disci_Hekim_Program.HastaServis.TCGetirRequestBody Body;
        
        public TCGetirRequest() {
        }
        
        public TCGetirRequest(Disci_Hekim_Program.HastaServis.TCGetirRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class TCGetirRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public TCGetirRequestBody() {
        }
        
        public TCGetirRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TCGetirResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TCGetirResponse", Namespace="http://tempuri.org/", Order=0)]
        public Disci_Hekim_Program.HastaServis.TCGetirResponseBody Body;
        
        public TCGetirResponse() {
        }
        
        public TCGetirResponse(Disci_Hekim_Program.HastaServis.TCGetirResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class TCGetirResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string TCGetirResult;
        
        public TCGetirResponseBody() {
        }
        
        public TCGetirResponseBody(string TCGetirResult) {
            this.TCGetirResult = TCGetirResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TelGetirRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TelGetir", Namespace="http://tempuri.org/", Order=0)]
        public Disci_Hekim_Program.HastaServis.TelGetirRequestBody Body;
        
        public TelGetirRequest() {
        }
        
        public TelGetirRequest(Disci_Hekim_Program.HastaServis.TelGetirRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class TelGetirRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public TelGetirRequestBody() {
        }
        
        public TelGetirRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TelGetirResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TelGetirResponse", Namespace="http://tempuri.org/", Order=0)]
        public Disci_Hekim_Program.HastaServis.TelGetirResponseBody Body;
        
        public TelGetirResponse() {
        }
        
        public TelGetirResponse(Disci_Hekim_Program.HastaServis.TelGetirResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class TelGetirResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string TelGetirResult;
        
        public TelGetirResponseBody() {
        }
        
        public TelGetirResponseBody(string TelGetirResult) {
            this.TelGetirResult = TelGetirResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MailGetirRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MailGetir", Namespace="http://tempuri.org/", Order=0)]
        public Disci_Hekim_Program.HastaServis.MailGetirRequestBody Body;
        
        public MailGetirRequest() {
        }
        
        public MailGetirRequest(Disci_Hekim_Program.HastaServis.MailGetirRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MailGetirRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public MailGetirRequestBody() {
        }
        
        public MailGetirRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MailGetirResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MailGetirResponse", Namespace="http://tempuri.org/", Order=0)]
        public Disci_Hekim_Program.HastaServis.MailGetirResponseBody Body;
        
        public MailGetirResponse() {
        }
        
        public MailGetirResponse(Disci_Hekim_Program.HastaServis.MailGetirResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MailGetirResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string MailGetirResult;
        
        public MailGetirResponseBody() {
        }
        
        public MailGetirResponseBody(string MailGetirResult) {
            this.MailGetirResult = MailGetirResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CinsyetGetirRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CinsyetGetir", Namespace="http://tempuri.org/", Order=0)]
        public Disci_Hekim_Program.HastaServis.CinsyetGetirRequestBody Body;
        
        public CinsyetGetirRequest() {
        }
        
        public CinsyetGetirRequest(Disci_Hekim_Program.HastaServis.CinsyetGetirRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CinsyetGetirRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public CinsyetGetirRequestBody() {
        }
        
        public CinsyetGetirRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CinsyetGetirResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CinsyetGetirResponse", Namespace="http://tempuri.org/", Order=0)]
        public Disci_Hekim_Program.HastaServis.CinsyetGetirResponseBody Body;
        
        public CinsyetGetirResponse() {
        }
        
        public CinsyetGetirResponse(Disci_Hekim_Program.HastaServis.CinsyetGetirResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CinsyetGetirResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CinsyetGetirResult;
        
        public CinsyetGetirResponseBody() {
        }
        
        public CinsyetGetirResponseBody(string CinsyetGetirResult) {
            this.CinsyetGetirResult = CinsyetGetirResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IDGetirRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IDGetir", Namespace="http://tempuri.org/", Order=0)]
        public Disci_Hekim_Program.HastaServis.IDGetirRequestBody Body;
        
        public IDGetirRequest() {
        }
        
        public IDGetirRequest(Disci_Hekim_Program.HastaServis.IDGetirRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class IDGetirRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string TC;
        
        public IDGetirRequestBody() {
        }
        
        public IDGetirRequestBody(string TC) {
            this.TC = TC;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IDGetirResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IDGetirResponse", Namespace="http://tempuri.org/", Order=0)]
        public Disci_Hekim_Program.HastaServis.IDGetirResponseBody Body;
        
        public IDGetirResponse() {
        }
        
        public IDGetirResponse(Disci_Hekim_Program.HastaServis.IDGetirResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class IDGetirResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int IDGetirResult;
        
        public IDGetirResponseBody() {
        }
        
        public IDGetirResponseBody(int IDGetirResult) {
            this.IDGetirResult = IDGetirResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DurumGuncelleRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DurumGuncelle", Namespace="http://tempuri.org/", Order=0)]
        public Disci_Hekim_Program.HastaServis.DurumGuncelleRequestBody Body;
        
        public DurumGuncelleRequest() {
        }
        
        public DurumGuncelleRequest(Disci_Hekim_Program.HastaServis.DurumGuncelleRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DurumGuncelleRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string durum;
        
        public DurumGuncelleRequestBody() {
        }
        
        public DurumGuncelleRequestBody(int id, string durum) {
            this.id = id;
            this.durum = durum;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DurumGuncelleResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DurumGuncelleResponse", Namespace="http://tempuri.org/", Order=0)]
        public Disci_Hekim_Program.HastaServis.DurumGuncelleResponseBody Body;
        
        public DurumGuncelleResponse() {
        }
        
        public DurumGuncelleResponse(Disci_Hekim_Program.HastaServis.DurumGuncelleResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class DurumGuncelleResponseBody {
        
        public DurumGuncelleResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IsimGetirResepsiyonRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IsimGetirResepsiyon", Namespace="http://tempuri.org/", Order=0)]
        public Disci_Hekim_Program.HastaServis.IsimGetirResepsiyonRequestBody Body;
        
        public IsimGetirResepsiyonRequest() {
        }
        
        public IsimGetirResepsiyonRequest(Disci_Hekim_Program.HastaServis.IsimGetirResepsiyonRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class IsimGetirResepsiyonRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public IsimGetirResepsiyonRequestBody() {
        }
        
        public IsimGetirResepsiyonRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IsimGetirResepsiyonResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IsimGetirResepsiyonResponse", Namespace="http://tempuri.org/", Order=0)]
        public Disci_Hekim_Program.HastaServis.IsimGetirResepsiyonResponseBody Body;
        
        public IsimGetirResepsiyonResponse() {
        }
        
        public IsimGetirResepsiyonResponse(Disci_Hekim_Program.HastaServis.IsimGetirResepsiyonResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class IsimGetirResepsiyonResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string IsimGetirResepsiyonResult;
        
        public IsimGetirResepsiyonResponseBody() {
        }
        
        public IsimGetirResepsiyonResponseBody(string IsimGetirResepsiyonResult) {
            this.IsimGetirResepsiyonResult = IsimGetirResepsiyonResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SoyadGetirResepsiyonRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SoyadGetirResepsiyon", Namespace="http://tempuri.org/", Order=0)]
        public Disci_Hekim_Program.HastaServis.SoyadGetirResepsiyonRequestBody Body;
        
        public SoyadGetirResepsiyonRequest() {
        }
        
        public SoyadGetirResepsiyonRequest(Disci_Hekim_Program.HastaServis.SoyadGetirResepsiyonRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SoyadGetirResepsiyonRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public SoyadGetirResepsiyonRequestBody() {
        }
        
        public SoyadGetirResepsiyonRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SoyadGetirResepsiyonResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SoyadGetirResepsiyonResponse", Namespace="http://tempuri.org/", Order=0)]
        public Disci_Hekim_Program.HastaServis.SoyadGetirResepsiyonResponseBody Body;
        
        public SoyadGetirResepsiyonResponse() {
        }
        
        public SoyadGetirResepsiyonResponse(Disci_Hekim_Program.HastaServis.SoyadGetirResepsiyonResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SoyadGetirResepsiyonResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SoyadGetirResepsiyonResult;
        
        public SoyadGetirResepsiyonResponseBody() {
        }
        
        public SoyadGetirResepsiyonResponseBody(string SoyadGetirResepsiyonResult) {
            this.SoyadGetirResepsiyonResult = SoyadGetirResepsiyonResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TCGetirResepsiyonRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TCGetirResepsiyon", Namespace="http://tempuri.org/", Order=0)]
        public Disci_Hekim_Program.HastaServis.TCGetirResepsiyonRequestBody Body;
        
        public TCGetirResepsiyonRequest() {
        }
        
        public TCGetirResepsiyonRequest(Disci_Hekim_Program.HastaServis.TCGetirResepsiyonRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class TCGetirResepsiyonRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public TCGetirResepsiyonRequestBody() {
        }
        
        public TCGetirResepsiyonRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TCGetirResepsiyonResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TCGetirResepsiyonResponse", Namespace="http://tempuri.org/", Order=0)]
        public Disci_Hekim_Program.HastaServis.TCGetirResepsiyonResponseBody Body;
        
        public TCGetirResepsiyonResponse() {
        }
        
        public TCGetirResepsiyonResponse(Disci_Hekim_Program.HastaServis.TCGetirResepsiyonResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class TCGetirResepsiyonResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string TCGetirResepsiyonResult;
        
        public TCGetirResepsiyonResponseBody() {
        }
        
        public TCGetirResepsiyonResponseBody(string TCGetirResepsiyonResult) {
            this.TCGetirResepsiyonResult = TCGetirResepsiyonResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HastaListeleRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HastaListele", Namespace="http://tempuri.org/", Order=0)]
        public Disci_Hekim_Program.HastaServis.HastaListeleRequestBody Body;
        
        public HastaListeleRequest() {
        }
        
        public HastaListeleRequest(Disci_Hekim_Program.HastaServis.HastaListeleRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HastaListeleRequestBody {
        
        public HastaListeleRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HastaListeleResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HastaListeleResponse", Namespace="http://tempuri.org/", Order=0)]
        public Disci_Hekim_Program.HastaServis.HastaListeleResponseBody Body;
        
        public HastaListeleResponse() {
        }
        
        public HastaListeleResponse(Disci_Hekim_Program.HastaServis.HastaListeleResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HastaListeleResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Disci_Hekim_Program.HastaServis.Hastalar[] HastaListeleResult;
        
        public HastaListeleResponseBody() {
        }
        
        public HastaListeleResponseBody(Disci_Hekim_Program.HastaServis.Hastalar[] HastaListeleResult) {
            this.HastaListeleResult = HastaListeleResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HastaListeleTCGoreRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HastaListeleTCGore", Namespace="http://tempuri.org/", Order=0)]
        public Disci_Hekim_Program.HastaServis.HastaListeleTCGoreRequestBody Body;
        
        public HastaListeleTCGoreRequest() {
        }
        
        public HastaListeleTCGoreRequest(Disci_Hekim_Program.HastaServis.HastaListeleTCGoreRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HastaListeleTCGoreRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string tc;
        
        public HastaListeleTCGoreRequestBody() {
        }
        
        public HastaListeleTCGoreRequestBody(string tc) {
            this.tc = tc;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HastaListeleTCGoreResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HastaListeleTCGoreResponse", Namespace="http://tempuri.org/", Order=0)]
        public Disci_Hekim_Program.HastaServis.HastaListeleTCGoreResponseBody Body;
        
        public HastaListeleTCGoreResponse() {
        }
        
        public HastaListeleTCGoreResponse(Disci_Hekim_Program.HastaServis.HastaListeleTCGoreResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HastaListeleTCGoreResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Disci_Hekim_Program.HastaServis.Hastalar[] HastaListeleTCGoreResult;
        
        public HastaListeleTCGoreResponseBody() {
        }
        
        public HastaListeleTCGoreResponseBody(Disci_Hekim_Program.HastaServis.Hastalar[] HastaListeleTCGoreResult) {
            this.HastaListeleTCGoreResult = HastaListeleTCGoreResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HastaEkleRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HastaEkle", Namespace="http://tempuri.org/", Order=0)]
        public Disci_Hekim_Program.HastaServis.HastaEkleRequestBody Body;
        
        public HastaEkleRequest() {
        }
        
        public HastaEkleRequest(Disci_Hekim_Program.HastaServis.HastaEkleRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HastaEkleRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string hastad;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string hastasoyad;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string tc;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string tel;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string mail;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string durum;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public int yas;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string cinsiyet;
        
        public HastaEkleRequestBody() {
        }
        
        public HastaEkleRequestBody(string hastad, string hastasoyad, string tc, string tel, string mail, string durum, int yas, string cinsiyet) {
            this.hastad = hastad;
            this.hastasoyad = hastasoyad;
            this.tc = tc;
            this.tel = tel;
            this.mail = mail;
            this.durum = durum;
            this.yas = yas;
            this.cinsiyet = cinsiyet;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HastaEkleResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HastaEkleResponse", Namespace="http://tempuri.org/", Order=0)]
        public Disci_Hekim_Program.HastaServis.HastaEkleResponseBody Body;
        
        public HastaEkleResponse() {
        }
        
        public HastaEkleResponse(Disci_Hekim_Program.HastaServis.HastaEkleResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HastaEkleResponseBody {
        
        public HastaEkleResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HastaGuncelleRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HastaGuncelle", Namespace="http://tempuri.org/", Order=0)]
        public Disci_Hekim_Program.HastaServis.HastaGuncelleRequestBody Body;
        
        public HastaGuncelleRequest() {
        }
        
        public HastaGuncelleRequest(Disci_Hekim_Program.HastaServis.HastaGuncelleRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HastaGuncelleRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string hastad;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string hastasoyad;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string tc;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string tel;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string mail;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string durum;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public int yas;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string cinsiyet;
        
        public HastaGuncelleRequestBody() {
        }
        
        public HastaGuncelleRequestBody(int id, string hastad, string hastasoyad, string tc, string tel, string mail, string durum, int yas, string cinsiyet) {
            this.id = id;
            this.hastad = hastad;
            this.hastasoyad = hastasoyad;
            this.tc = tc;
            this.tel = tel;
            this.mail = mail;
            this.durum = durum;
            this.yas = yas;
            this.cinsiyet = cinsiyet;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HastaGuncelleResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HastaGuncelleResponse", Namespace="http://tempuri.org/", Order=0)]
        public Disci_Hekim_Program.HastaServis.HastaGuncelleResponseBody Body;
        
        public HastaGuncelleResponse() {
        }
        
        public HastaGuncelleResponse(Disci_Hekim_Program.HastaServis.HastaGuncelleResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HastaGuncelleResponseBody {
        
        public HastaGuncelleResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface HastaSoapChannel : Disci_Hekim_Program.HastaServis.HastaSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HastaSoapClient : System.ServiceModel.ClientBase<Disci_Hekim_Program.HastaServis.HastaSoap>, Disci_Hekim_Program.HastaServis.HastaSoap {
        
        public HastaSoapClient() {
        }
        
        public HastaSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HastaSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HastaSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HastaSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Disci_Hekim_Program.HastaServis.IsimGetirResponse Disci_Hekim_Program.HastaServis.HastaSoap.IsimGetir(Disci_Hekim_Program.HastaServis.IsimGetirRequest request) {
            return base.Channel.IsimGetir(request);
        }
        
        public string IsimGetir(int id) {
            Disci_Hekim_Program.HastaServis.IsimGetirRequest inValue = new Disci_Hekim_Program.HastaServis.IsimGetirRequest();
            inValue.Body = new Disci_Hekim_Program.HastaServis.IsimGetirRequestBody();
            inValue.Body.id = id;
            Disci_Hekim_Program.HastaServis.IsimGetirResponse retVal = ((Disci_Hekim_Program.HastaServis.HastaSoap)(this)).IsimGetir(inValue);
            return retVal.Body.IsimGetirResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Disci_Hekim_Program.HastaServis.IsimGetirResponse> Disci_Hekim_Program.HastaServis.HastaSoap.IsimGetirAsync(Disci_Hekim_Program.HastaServis.IsimGetirRequest request) {
            return base.Channel.IsimGetirAsync(request);
        }
        
        public System.Threading.Tasks.Task<Disci_Hekim_Program.HastaServis.IsimGetirResponse> IsimGetirAsync(int id) {
            Disci_Hekim_Program.HastaServis.IsimGetirRequest inValue = new Disci_Hekim_Program.HastaServis.IsimGetirRequest();
            inValue.Body = new Disci_Hekim_Program.HastaServis.IsimGetirRequestBody();
            inValue.Body.id = id;
            return ((Disci_Hekim_Program.HastaServis.HastaSoap)(this)).IsimGetirAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Disci_Hekim_Program.HastaServis.SoyadResponse Disci_Hekim_Program.HastaServis.HastaSoap.Soyad(Disci_Hekim_Program.HastaServis.SoyadRequest request) {
            return base.Channel.Soyad(request);
        }
        
        public string Soyad(int id) {
            Disci_Hekim_Program.HastaServis.SoyadRequest inValue = new Disci_Hekim_Program.HastaServis.SoyadRequest();
            inValue.Body = new Disci_Hekim_Program.HastaServis.SoyadRequestBody();
            inValue.Body.id = id;
            Disci_Hekim_Program.HastaServis.SoyadResponse retVal = ((Disci_Hekim_Program.HastaServis.HastaSoap)(this)).Soyad(inValue);
            return retVal.Body.SoyadResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Disci_Hekim_Program.HastaServis.SoyadResponse> Disci_Hekim_Program.HastaServis.HastaSoap.SoyadAsync(Disci_Hekim_Program.HastaServis.SoyadRequest request) {
            return base.Channel.SoyadAsync(request);
        }
        
        public System.Threading.Tasks.Task<Disci_Hekim_Program.HastaServis.SoyadResponse> SoyadAsync(int id) {
            Disci_Hekim_Program.HastaServis.SoyadRequest inValue = new Disci_Hekim_Program.HastaServis.SoyadRequest();
            inValue.Body = new Disci_Hekim_Program.HastaServis.SoyadRequestBody();
            inValue.Body.id = id;
            return ((Disci_Hekim_Program.HastaServis.HastaSoap)(this)).SoyadAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Disci_Hekim_Program.HastaServis.TCGetirResponse Disci_Hekim_Program.HastaServis.HastaSoap.TCGetir(Disci_Hekim_Program.HastaServis.TCGetirRequest request) {
            return base.Channel.TCGetir(request);
        }
        
        public string TCGetir(int id) {
            Disci_Hekim_Program.HastaServis.TCGetirRequest inValue = new Disci_Hekim_Program.HastaServis.TCGetirRequest();
            inValue.Body = new Disci_Hekim_Program.HastaServis.TCGetirRequestBody();
            inValue.Body.id = id;
            Disci_Hekim_Program.HastaServis.TCGetirResponse retVal = ((Disci_Hekim_Program.HastaServis.HastaSoap)(this)).TCGetir(inValue);
            return retVal.Body.TCGetirResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Disci_Hekim_Program.HastaServis.TCGetirResponse> Disci_Hekim_Program.HastaServis.HastaSoap.TCGetirAsync(Disci_Hekim_Program.HastaServis.TCGetirRequest request) {
            return base.Channel.TCGetirAsync(request);
        }
        
        public System.Threading.Tasks.Task<Disci_Hekim_Program.HastaServis.TCGetirResponse> TCGetirAsync(int id) {
            Disci_Hekim_Program.HastaServis.TCGetirRequest inValue = new Disci_Hekim_Program.HastaServis.TCGetirRequest();
            inValue.Body = new Disci_Hekim_Program.HastaServis.TCGetirRequestBody();
            inValue.Body.id = id;
            return ((Disci_Hekim_Program.HastaServis.HastaSoap)(this)).TCGetirAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Disci_Hekim_Program.HastaServis.TelGetirResponse Disci_Hekim_Program.HastaServis.HastaSoap.TelGetir(Disci_Hekim_Program.HastaServis.TelGetirRequest request) {
            return base.Channel.TelGetir(request);
        }
        
        public string TelGetir(int id) {
            Disci_Hekim_Program.HastaServis.TelGetirRequest inValue = new Disci_Hekim_Program.HastaServis.TelGetirRequest();
            inValue.Body = new Disci_Hekim_Program.HastaServis.TelGetirRequestBody();
            inValue.Body.id = id;
            Disci_Hekim_Program.HastaServis.TelGetirResponse retVal = ((Disci_Hekim_Program.HastaServis.HastaSoap)(this)).TelGetir(inValue);
            return retVal.Body.TelGetirResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Disci_Hekim_Program.HastaServis.TelGetirResponse> Disci_Hekim_Program.HastaServis.HastaSoap.TelGetirAsync(Disci_Hekim_Program.HastaServis.TelGetirRequest request) {
            return base.Channel.TelGetirAsync(request);
        }
        
        public System.Threading.Tasks.Task<Disci_Hekim_Program.HastaServis.TelGetirResponse> TelGetirAsync(int id) {
            Disci_Hekim_Program.HastaServis.TelGetirRequest inValue = new Disci_Hekim_Program.HastaServis.TelGetirRequest();
            inValue.Body = new Disci_Hekim_Program.HastaServis.TelGetirRequestBody();
            inValue.Body.id = id;
            return ((Disci_Hekim_Program.HastaServis.HastaSoap)(this)).TelGetirAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Disci_Hekim_Program.HastaServis.MailGetirResponse Disci_Hekim_Program.HastaServis.HastaSoap.MailGetir(Disci_Hekim_Program.HastaServis.MailGetirRequest request) {
            return base.Channel.MailGetir(request);
        }
        
        public string MailGetir(int id) {
            Disci_Hekim_Program.HastaServis.MailGetirRequest inValue = new Disci_Hekim_Program.HastaServis.MailGetirRequest();
            inValue.Body = new Disci_Hekim_Program.HastaServis.MailGetirRequestBody();
            inValue.Body.id = id;
            Disci_Hekim_Program.HastaServis.MailGetirResponse retVal = ((Disci_Hekim_Program.HastaServis.HastaSoap)(this)).MailGetir(inValue);
            return retVal.Body.MailGetirResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Disci_Hekim_Program.HastaServis.MailGetirResponse> Disci_Hekim_Program.HastaServis.HastaSoap.MailGetirAsync(Disci_Hekim_Program.HastaServis.MailGetirRequest request) {
            return base.Channel.MailGetirAsync(request);
        }
        
        public System.Threading.Tasks.Task<Disci_Hekim_Program.HastaServis.MailGetirResponse> MailGetirAsync(int id) {
            Disci_Hekim_Program.HastaServis.MailGetirRequest inValue = new Disci_Hekim_Program.HastaServis.MailGetirRequest();
            inValue.Body = new Disci_Hekim_Program.HastaServis.MailGetirRequestBody();
            inValue.Body.id = id;
            return ((Disci_Hekim_Program.HastaServis.HastaSoap)(this)).MailGetirAsync(inValue);
        }
        
        public int YasGetir(int id) {
            return base.Channel.YasGetir(id);
        }
        
        public System.Threading.Tasks.Task<int> YasGetirAsync(int id) {
            return base.Channel.YasGetirAsync(id);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Disci_Hekim_Program.HastaServis.CinsyetGetirResponse Disci_Hekim_Program.HastaServis.HastaSoap.CinsyetGetir(Disci_Hekim_Program.HastaServis.CinsyetGetirRequest request) {
            return base.Channel.CinsyetGetir(request);
        }
        
        public string CinsyetGetir(int id) {
            Disci_Hekim_Program.HastaServis.CinsyetGetirRequest inValue = new Disci_Hekim_Program.HastaServis.CinsyetGetirRequest();
            inValue.Body = new Disci_Hekim_Program.HastaServis.CinsyetGetirRequestBody();
            inValue.Body.id = id;
            Disci_Hekim_Program.HastaServis.CinsyetGetirResponse retVal = ((Disci_Hekim_Program.HastaServis.HastaSoap)(this)).CinsyetGetir(inValue);
            return retVal.Body.CinsyetGetirResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Disci_Hekim_Program.HastaServis.CinsyetGetirResponse> Disci_Hekim_Program.HastaServis.HastaSoap.CinsyetGetirAsync(Disci_Hekim_Program.HastaServis.CinsyetGetirRequest request) {
            return base.Channel.CinsyetGetirAsync(request);
        }
        
        public System.Threading.Tasks.Task<Disci_Hekim_Program.HastaServis.CinsyetGetirResponse> CinsyetGetirAsync(int id) {
            Disci_Hekim_Program.HastaServis.CinsyetGetirRequest inValue = new Disci_Hekim_Program.HastaServis.CinsyetGetirRequest();
            inValue.Body = new Disci_Hekim_Program.HastaServis.CinsyetGetirRequestBody();
            inValue.Body.id = id;
            return ((Disci_Hekim_Program.HastaServis.HastaSoap)(this)).CinsyetGetirAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Disci_Hekim_Program.HastaServis.IDGetirResponse Disci_Hekim_Program.HastaServis.HastaSoap.IDGetir(Disci_Hekim_Program.HastaServis.IDGetirRequest request) {
            return base.Channel.IDGetir(request);
        }
        
        public int IDGetir(string TC) {
            Disci_Hekim_Program.HastaServis.IDGetirRequest inValue = new Disci_Hekim_Program.HastaServis.IDGetirRequest();
            inValue.Body = new Disci_Hekim_Program.HastaServis.IDGetirRequestBody();
            inValue.Body.TC = TC;
            Disci_Hekim_Program.HastaServis.IDGetirResponse retVal = ((Disci_Hekim_Program.HastaServis.HastaSoap)(this)).IDGetir(inValue);
            return retVal.Body.IDGetirResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Disci_Hekim_Program.HastaServis.IDGetirResponse> Disci_Hekim_Program.HastaServis.HastaSoap.IDGetirAsync(Disci_Hekim_Program.HastaServis.IDGetirRequest request) {
            return base.Channel.IDGetirAsync(request);
        }
        
        public System.Threading.Tasks.Task<Disci_Hekim_Program.HastaServis.IDGetirResponse> IDGetirAsync(string TC) {
            Disci_Hekim_Program.HastaServis.IDGetirRequest inValue = new Disci_Hekim_Program.HastaServis.IDGetirRequest();
            inValue.Body = new Disci_Hekim_Program.HastaServis.IDGetirRequestBody();
            inValue.Body.TC = TC;
            return ((Disci_Hekim_Program.HastaServis.HastaSoap)(this)).IDGetirAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Disci_Hekim_Program.HastaServis.DurumGuncelleResponse Disci_Hekim_Program.HastaServis.HastaSoap.DurumGuncelle(Disci_Hekim_Program.HastaServis.DurumGuncelleRequest request) {
            return base.Channel.DurumGuncelle(request);
        }
        
        public void DurumGuncelle(int id, string durum) {
            Disci_Hekim_Program.HastaServis.DurumGuncelleRequest inValue = new Disci_Hekim_Program.HastaServis.DurumGuncelleRequest();
            inValue.Body = new Disci_Hekim_Program.HastaServis.DurumGuncelleRequestBody();
            inValue.Body.id = id;
            inValue.Body.durum = durum;
            Disci_Hekim_Program.HastaServis.DurumGuncelleResponse retVal = ((Disci_Hekim_Program.HastaServis.HastaSoap)(this)).DurumGuncelle(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Disci_Hekim_Program.HastaServis.DurumGuncelleResponse> Disci_Hekim_Program.HastaServis.HastaSoap.DurumGuncelleAsync(Disci_Hekim_Program.HastaServis.DurumGuncelleRequest request) {
            return base.Channel.DurumGuncelleAsync(request);
        }
        
        public System.Threading.Tasks.Task<Disci_Hekim_Program.HastaServis.DurumGuncelleResponse> DurumGuncelleAsync(int id, string durum) {
            Disci_Hekim_Program.HastaServis.DurumGuncelleRequest inValue = new Disci_Hekim_Program.HastaServis.DurumGuncelleRequest();
            inValue.Body = new Disci_Hekim_Program.HastaServis.DurumGuncelleRequestBody();
            inValue.Body.id = id;
            inValue.Body.durum = durum;
            return ((Disci_Hekim_Program.HastaServis.HastaSoap)(this)).DurumGuncelleAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Disci_Hekim_Program.HastaServis.IsimGetirResepsiyonResponse Disci_Hekim_Program.HastaServis.HastaSoap.IsimGetirResepsiyon(Disci_Hekim_Program.HastaServis.IsimGetirResepsiyonRequest request) {
            return base.Channel.IsimGetirResepsiyon(request);
        }
        
        public string IsimGetirResepsiyon(int id) {
            Disci_Hekim_Program.HastaServis.IsimGetirResepsiyonRequest inValue = new Disci_Hekim_Program.HastaServis.IsimGetirResepsiyonRequest();
            inValue.Body = new Disci_Hekim_Program.HastaServis.IsimGetirResepsiyonRequestBody();
            inValue.Body.id = id;
            Disci_Hekim_Program.HastaServis.IsimGetirResepsiyonResponse retVal = ((Disci_Hekim_Program.HastaServis.HastaSoap)(this)).IsimGetirResepsiyon(inValue);
            return retVal.Body.IsimGetirResepsiyonResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Disci_Hekim_Program.HastaServis.IsimGetirResepsiyonResponse> Disci_Hekim_Program.HastaServis.HastaSoap.IsimGetirResepsiyonAsync(Disci_Hekim_Program.HastaServis.IsimGetirResepsiyonRequest request) {
            return base.Channel.IsimGetirResepsiyonAsync(request);
        }
        
        public System.Threading.Tasks.Task<Disci_Hekim_Program.HastaServis.IsimGetirResepsiyonResponse> IsimGetirResepsiyonAsync(int id) {
            Disci_Hekim_Program.HastaServis.IsimGetirResepsiyonRequest inValue = new Disci_Hekim_Program.HastaServis.IsimGetirResepsiyonRequest();
            inValue.Body = new Disci_Hekim_Program.HastaServis.IsimGetirResepsiyonRequestBody();
            inValue.Body.id = id;
            return ((Disci_Hekim_Program.HastaServis.HastaSoap)(this)).IsimGetirResepsiyonAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Disci_Hekim_Program.HastaServis.SoyadGetirResepsiyonResponse Disci_Hekim_Program.HastaServis.HastaSoap.SoyadGetirResepsiyon(Disci_Hekim_Program.HastaServis.SoyadGetirResepsiyonRequest request) {
            return base.Channel.SoyadGetirResepsiyon(request);
        }
        
        public string SoyadGetirResepsiyon(int id) {
            Disci_Hekim_Program.HastaServis.SoyadGetirResepsiyonRequest inValue = new Disci_Hekim_Program.HastaServis.SoyadGetirResepsiyonRequest();
            inValue.Body = new Disci_Hekim_Program.HastaServis.SoyadGetirResepsiyonRequestBody();
            inValue.Body.id = id;
            Disci_Hekim_Program.HastaServis.SoyadGetirResepsiyonResponse retVal = ((Disci_Hekim_Program.HastaServis.HastaSoap)(this)).SoyadGetirResepsiyon(inValue);
            return retVal.Body.SoyadGetirResepsiyonResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Disci_Hekim_Program.HastaServis.SoyadGetirResepsiyonResponse> Disci_Hekim_Program.HastaServis.HastaSoap.SoyadGetirResepsiyonAsync(Disci_Hekim_Program.HastaServis.SoyadGetirResepsiyonRequest request) {
            return base.Channel.SoyadGetirResepsiyonAsync(request);
        }
        
        public System.Threading.Tasks.Task<Disci_Hekim_Program.HastaServis.SoyadGetirResepsiyonResponse> SoyadGetirResepsiyonAsync(int id) {
            Disci_Hekim_Program.HastaServis.SoyadGetirResepsiyonRequest inValue = new Disci_Hekim_Program.HastaServis.SoyadGetirResepsiyonRequest();
            inValue.Body = new Disci_Hekim_Program.HastaServis.SoyadGetirResepsiyonRequestBody();
            inValue.Body.id = id;
            return ((Disci_Hekim_Program.HastaServis.HastaSoap)(this)).SoyadGetirResepsiyonAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Disci_Hekim_Program.HastaServis.TCGetirResepsiyonResponse Disci_Hekim_Program.HastaServis.HastaSoap.TCGetirResepsiyon(Disci_Hekim_Program.HastaServis.TCGetirResepsiyonRequest request) {
            return base.Channel.TCGetirResepsiyon(request);
        }
        
        public string TCGetirResepsiyon(int id) {
            Disci_Hekim_Program.HastaServis.TCGetirResepsiyonRequest inValue = new Disci_Hekim_Program.HastaServis.TCGetirResepsiyonRequest();
            inValue.Body = new Disci_Hekim_Program.HastaServis.TCGetirResepsiyonRequestBody();
            inValue.Body.id = id;
            Disci_Hekim_Program.HastaServis.TCGetirResepsiyonResponse retVal = ((Disci_Hekim_Program.HastaServis.HastaSoap)(this)).TCGetirResepsiyon(inValue);
            return retVal.Body.TCGetirResepsiyonResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Disci_Hekim_Program.HastaServis.TCGetirResepsiyonResponse> Disci_Hekim_Program.HastaServis.HastaSoap.TCGetirResepsiyonAsync(Disci_Hekim_Program.HastaServis.TCGetirResepsiyonRequest request) {
            return base.Channel.TCGetirResepsiyonAsync(request);
        }
        
        public System.Threading.Tasks.Task<Disci_Hekim_Program.HastaServis.TCGetirResepsiyonResponse> TCGetirResepsiyonAsync(int id) {
            Disci_Hekim_Program.HastaServis.TCGetirResepsiyonRequest inValue = new Disci_Hekim_Program.HastaServis.TCGetirResepsiyonRequest();
            inValue.Body = new Disci_Hekim_Program.HastaServis.TCGetirResepsiyonRequestBody();
            inValue.Body.id = id;
            return ((Disci_Hekim_Program.HastaServis.HastaSoap)(this)).TCGetirResepsiyonAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Disci_Hekim_Program.HastaServis.HastaListeleResponse Disci_Hekim_Program.HastaServis.HastaSoap.HastaListele(Disci_Hekim_Program.HastaServis.HastaListeleRequest request) {
            return base.Channel.HastaListele(request);
        }
        
        public Disci_Hekim_Program.HastaServis.Hastalar[] HastaListele() {
            Disci_Hekim_Program.HastaServis.HastaListeleRequest inValue = new Disci_Hekim_Program.HastaServis.HastaListeleRequest();
            inValue.Body = new Disci_Hekim_Program.HastaServis.HastaListeleRequestBody();
            Disci_Hekim_Program.HastaServis.HastaListeleResponse retVal = ((Disci_Hekim_Program.HastaServis.HastaSoap)(this)).HastaListele(inValue);
            return retVal.Body.HastaListeleResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Disci_Hekim_Program.HastaServis.HastaListeleResponse> Disci_Hekim_Program.HastaServis.HastaSoap.HastaListeleAsync(Disci_Hekim_Program.HastaServis.HastaListeleRequest request) {
            return base.Channel.HastaListeleAsync(request);
        }
        
        public System.Threading.Tasks.Task<Disci_Hekim_Program.HastaServis.HastaListeleResponse> HastaListeleAsync() {
            Disci_Hekim_Program.HastaServis.HastaListeleRequest inValue = new Disci_Hekim_Program.HastaServis.HastaListeleRequest();
            inValue.Body = new Disci_Hekim_Program.HastaServis.HastaListeleRequestBody();
            return ((Disci_Hekim_Program.HastaServis.HastaSoap)(this)).HastaListeleAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Disci_Hekim_Program.HastaServis.HastaListeleTCGoreResponse Disci_Hekim_Program.HastaServis.HastaSoap.HastaListeleTCGore(Disci_Hekim_Program.HastaServis.HastaListeleTCGoreRequest request) {
            return base.Channel.HastaListeleTCGore(request);
        }
        
        public Disci_Hekim_Program.HastaServis.Hastalar[] HastaListeleTCGore(string tc) {
            Disci_Hekim_Program.HastaServis.HastaListeleTCGoreRequest inValue = new Disci_Hekim_Program.HastaServis.HastaListeleTCGoreRequest();
            inValue.Body = new Disci_Hekim_Program.HastaServis.HastaListeleTCGoreRequestBody();
            inValue.Body.tc = tc;
            Disci_Hekim_Program.HastaServis.HastaListeleTCGoreResponse retVal = ((Disci_Hekim_Program.HastaServis.HastaSoap)(this)).HastaListeleTCGore(inValue);
            return retVal.Body.HastaListeleTCGoreResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Disci_Hekim_Program.HastaServis.HastaListeleTCGoreResponse> Disci_Hekim_Program.HastaServis.HastaSoap.HastaListeleTCGoreAsync(Disci_Hekim_Program.HastaServis.HastaListeleTCGoreRequest request) {
            return base.Channel.HastaListeleTCGoreAsync(request);
        }
        
        public System.Threading.Tasks.Task<Disci_Hekim_Program.HastaServis.HastaListeleTCGoreResponse> HastaListeleTCGoreAsync(string tc) {
            Disci_Hekim_Program.HastaServis.HastaListeleTCGoreRequest inValue = new Disci_Hekim_Program.HastaServis.HastaListeleTCGoreRequest();
            inValue.Body = new Disci_Hekim_Program.HastaServis.HastaListeleTCGoreRequestBody();
            inValue.Body.tc = tc;
            return ((Disci_Hekim_Program.HastaServis.HastaSoap)(this)).HastaListeleTCGoreAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Disci_Hekim_Program.HastaServis.HastaEkleResponse Disci_Hekim_Program.HastaServis.HastaSoap.HastaEkle(Disci_Hekim_Program.HastaServis.HastaEkleRequest request) {
            return base.Channel.HastaEkle(request);
        }
        
        public void HastaEkle(string hastad, string hastasoyad, string tc, string tel, string mail, string durum, int yas, string cinsiyet) {
            Disci_Hekim_Program.HastaServis.HastaEkleRequest inValue = new Disci_Hekim_Program.HastaServis.HastaEkleRequest();
            inValue.Body = new Disci_Hekim_Program.HastaServis.HastaEkleRequestBody();
            inValue.Body.hastad = hastad;
            inValue.Body.hastasoyad = hastasoyad;
            inValue.Body.tc = tc;
            inValue.Body.tel = tel;
            inValue.Body.mail = mail;
            inValue.Body.durum = durum;
            inValue.Body.yas = yas;
            inValue.Body.cinsiyet = cinsiyet;
            Disci_Hekim_Program.HastaServis.HastaEkleResponse retVal = ((Disci_Hekim_Program.HastaServis.HastaSoap)(this)).HastaEkle(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Disci_Hekim_Program.HastaServis.HastaEkleResponse> Disci_Hekim_Program.HastaServis.HastaSoap.HastaEkleAsync(Disci_Hekim_Program.HastaServis.HastaEkleRequest request) {
            return base.Channel.HastaEkleAsync(request);
        }
        
        public System.Threading.Tasks.Task<Disci_Hekim_Program.HastaServis.HastaEkleResponse> HastaEkleAsync(string hastad, string hastasoyad, string tc, string tel, string mail, string durum, int yas, string cinsiyet) {
            Disci_Hekim_Program.HastaServis.HastaEkleRequest inValue = new Disci_Hekim_Program.HastaServis.HastaEkleRequest();
            inValue.Body = new Disci_Hekim_Program.HastaServis.HastaEkleRequestBody();
            inValue.Body.hastad = hastad;
            inValue.Body.hastasoyad = hastasoyad;
            inValue.Body.tc = tc;
            inValue.Body.tel = tel;
            inValue.Body.mail = mail;
            inValue.Body.durum = durum;
            inValue.Body.yas = yas;
            inValue.Body.cinsiyet = cinsiyet;
            return ((Disci_Hekim_Program.HastaServis.HastaSoap)(this)).HastaEkleAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Disci_Hekim_Program.HastaServis.HastaGuncelleResponse Disci_Hekim_Program.HastaServis.HastaSoap.HastaGuncelle(Disci_Hekim_Program.HastaServis.HastaGuncelleRequest request) {
            return base.Channel.HastaGuncelle(request);
        }
        
        public void HastaGuncelle(int id, string hastad, string hastasoyad, string tc, string tel, string mail, string durum, int yas, string cinsiyet) {
            Disci_Hekim_Program.HastaServis.HastaGuncelleRequest inValue = new Disci_Hekim_Program.HastaServis.HastaGuncelleRequest();
            inValue.Body = new Disci_Hekim_Program.HastaServis.HastaGuncelleRequestBody();
            inValue.Body.id = id;
            inValue.Body.hastad = hastad;
            inValue.Body.hastasoyad = hastasoyad;
            inValue.Body.tc = tc;
            inValue.Body.tel = tel;
            inValue.Body.mail = mail;
            inValue.Body.durum = durum;
            inValue.Body.yas = yas;
            inValue.Body.cinsiyet = cinsiyet;
            Disci_Hekim_Program.HastaServis.HastaGuncelleResponse retVal = ((Disci_Hekim_Program.HastaServis.HastaSoap)(this)).HastaGuncelle(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Disci_Hekim_Program.HastaServis.HastaGuncelleResponse> Disci_Hekim_Program.HastaServis.HastaSoap.HastaGuncelleAsync(Disci_Hekim_Program.HastaServis.HastaGuncelleRequest request) {
            return base.Channel.HastaGuncelleAsync(request);
        }
        
        public System.Threading.Tasks.Task<Disci_Hekim_Program.HastaServis.HastaGuncelleResponse> HastaGuncelleAsync(int id, string hastad, string hastasoyad, string tc, string tel, string mail, string durum, int yas, string cinsiyet) {
            Disci_Hekim_Program.HastaServis.HastaGuncelleRequest inValue = new Disci_Hekim_Program.HastaServis.HastaGuncelleRequest();
            inValue.Body = new Disci_Hekim_Program.HastaServis.HastaGuncelleRequestBody();
            inValue.Body.id = id;
            inValue.Body.hastad = hastad;
            inValue.Body.hastasoyad = hastasoyad;
            inValue.Body.tc = tc;
            inValue.Body.tel = tel;
            inValue.Body.mail = mail;
            inValue.Body.durum = durum;
            inValue.Body.yas = yas;
            inValue.Body.cinsiyet = cinsiyet;
            return ((Disci_Hekim_Program.HastaServis.HastaSoap)(this)).HastaGuncelleAsync(inValue);
        }
        
        public void hastasil(int id) {
            base.Channel.hastasil(id);
        }
        
        public System.Threading.Tasks.Task hastasilAsync(int id) {
            return base.Channel.hastasilAsync(id);
        }
        
        public void hekimegonder(int id, int hekimid) {
            base.Channel.hekimegonder(id, hekimid);
        }
        
        public System.Threading.Tasks.Task hekimegonderAsync(int id, int hekimid) {
            return base.Channel.hekimegonderAsync(id, hekimid);
        }
    }
}
