//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Disci_Hekim_Program.IslemServis {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Islem", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Islem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IslemIDField;
        
        private System.Nullable<int> HekimIDField;
        
        private System.Nullable<int> HastaIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HastaAdiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HastaSoyadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TCField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IslemAdiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TarihField;
        
        private System.Nullable<double> ToplamTutarField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int IslemID {
            get {
                return this.IslemIDField;
            }
            set {
                if ((this.IslemIDField.Equals(value) != true)) {
                    this.IslemIDField = value;
                    this.RaisePropertyChanged("IslemID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public System.Nullable<int> HekimID {
            get {
                return this.HekimIDField;
            }
            set {
                if ((this.HekimIDField.Equals(value) != true)) {
                    this.HekimIDField = value;
                    this.RaisePropertyChanged("HekimID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public System.Nullable<int> HastaID {
            get {
                return this.HastaIDField;
            }
            set {
                if ((this.HastaIDField.Equals(value) != true)) {
                    this.HastaIDField = value;
                    this.RaisePropertyChanged("HastaID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string HastaAdi {
            get {
                return this.HastaAdiField;
            }
            set {
                if ((object.ReferenceEquals(this.HastaAdiField, value) != true)) {
                    this.HastaAdiField = value;
                    this.RaisePropertyChanged("HastaAdi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string HastaSoyad {
            get {
                return this.HastaSoyadField;
            }
            set {
                if ((object.ReferenceEquals(this.HastaSoyadField, value) != true)) {
                    this.HastaSoyadField = value;
                    this.RaisePropertyChanged("HastaSoyad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string TC {
            get {
                return this.TCField;
            }
            set {
                if ((object.ReferenceEquals(this.TCField, value) != true)) {
                    this.TCField = value;
                    this.RaisePropertyChanged("TC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string IslemAdi {
            get {
                return this.IslemAdiField;
            }
            set {
                if ((object.ReferenceEquals(this.IslemAdiField, value) != true)) {
                    this.IslemAdiField = value;
                    this.RaisePropertyChanged("IslemAdi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string Tarih {
            get {
                return this.TarihField;
            }
            set {
                if ((object.ReferenceEquals(this.TarihField, value) != true)) {
                    this.TarihField = value;
                    this.RaisePropertyChanged("Tarih");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public System.Nullable<double> ToplamTutar {
            get {
                return this.ToplamTutarField;
            }
            set {
                if ((this.ToplamTutarField.Equals(value) != true)) {
                    this.ToplamTutarField = value;
                    this.RaisePropertyChanged("ToplamTutar");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="IslemServis.IslemlerSoap")]
    public interface IslemlerSoap {
        
        // CODEGEN: Generating message contract since element name GecmisIslemlerResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GecmisIslemler", ReplyAction="*")]
        Disci_Hekim_Program.IslemServis.GecmisIslemlerResponse GecmisIslemler(Disci_Hekim_Program.IslemServis.GecmisIslemlerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GecmisIslemler", ReplyAction="*")]
        System.Threading.Tasks.Task<Disci_Hekim_Program.IslemServis.GecmisIslemlerResponse> GecmisIslemlerAsync(Disci_Hekim_Program.IslemServis.GecmisIslemlerRequest request);
        
        // CODEGEN: Generating message contract since element name islemadi from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IslemOlusturVeIDGetir", ReplyAction="*")]
        Disci_Hekim_Program.IslemServis.IslemOlusturVeIDGetirResponse IslemOlusturVeIDGetir(Disci_Hekim_Program.IslemServis.IslemOlusturVeIDGetirRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IslemOlusturVeIDGetir", ReplyAction="*")]
        System.Threading.Tasks.Task<Disci_Hekim_Program.IslemServis.IslemOlusturVeIDGetirResponse> IslemOlusturVeIDGetirAsync(Disci_Hekim_Program.IslemServis.IslemOlusturVeIDGetirRequest request);
        
        // CODEGEN: Generating message contract since element name tarih from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TariheGoreVeriGetir", ReplyAction="*")]
        Disci_Hekim_Program.IslemServis.TariheGoreVeriGetirResponse TariheGoreVeriGetir(Disci_Hekim_Program.IslemServis.TariheGoreVeriGetirRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TariheGoreVeriGetir", ReplyAction="*")]
        System.Threading.Tasks.Task<Disci_Hekim_Program.IslemServis.TariheGoreVeriGetirResponse> TariheGoreVeriGetirAsync(Disci_Hekim_Program.IslemServis.TariheGoreVeriGetirRequest request);
        
        // CODEGEN: Generating message contract since element name IslemListeleResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IslemListele", ReplyAction="*")]
        Disci_Hekim_Program.IslemServis.IslemListeleResponse IslemListele(Disci_Hekim_Program.IslemServis.IslemListeleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IslemListele", ReplyAction="*")]
        System.Threading.Tasks.Task<Disci_Hekim_Program.IslemServis.IslemListeleResponse> IslemListeleAsync(Disci_Hekim_Program.IslemServis.IslemListeleRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GecmisIslemlerRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GecmisIslemler", Namespace="http://tempuri.org/", Order=0)]
        public Disci_Hekim_Program.IslemServis.GecmisIslemlerRequestBody Body;
        
        public GecmisIslemlerRequest() {
        }
        
        public GecmisIslemlerRequest(Disci_Hekim_Program.IslemServis.GecmisIslemlerRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GecmisIslemlerRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public GecmisIslemlerRequestBody() {
        }
        
        public GecmisIslemlerRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GecmisIslemlerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GecmisIslemlerResponse", Namespace="http://tempuri.org/", Order=0)]
        public Disci_Hekim_Program.IslemServis.GecmisIslemlerResponseBody Body;
        
        public GecmisIslemlerResponse() {
        }
        
        public GecmisIslemlerResponse(Disci_Hekim_Program.IslemServis.GecmisIslemlerResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GecmisIslemlerResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Disci_Hekim_Program.IslemServis.Islem[] GecmisIslemlerResult;
        
        public GecmisIslemlerResponseBody() {
        }
        
        public GecmisIslemlerResponseBody(Disci_Hekim_Program.IslemServis.Islem[] GecmisIslemlerResult) {
            this.GecmisIslemlerResult = GecmisIslemlerResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IslemOlusturVeIDGetirRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IslemOlusturVeIDGetir", Namespace="http://tempuri.org/", Order=0)]
        public Disci_Hekim_Program.IslemServis.IslemOlusturVeIDGetirRequestBody Body;
        
        public IslemOlusturVeIDGetirRequest() {
        }
        
        public IslemOlusturVeIDGetirRequest(Disci_Hekim_Program.IslemServis.IslemOlusturVeIDGetirRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class IslemOlusturVeIDGetirRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int hekimid;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int hastaid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string islemadi;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string tarih;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public double toplamtutar;
        
        public IslemOlusturVeIDGetirRequestBody() {
        }
        
        public IslemOlusturVeIDGetirRequestBody(int hekimid, int hastaid, string islemadi, string tarih, double toplamtutar) {
            this.hekimid = hekimid;
            this.hastaid = hastaid;
            this.islemadi = islemadi;
            this.tarih = tarih;
            this.toplamtutar = toplamtutar;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IslemOlusturVeIDGetirResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IslemOlusturVeIDGetirResponse", Namespace="http://tempuri.org/", Order=0)]
        public Disci_Hekim_Program.IslemServis.IslemOlusturVeIDGetirResponseBody Body;
        
        public IslemOlusturVeIDGetirResponse() {
        }
        
        public IslemOlusturVeIDGetirResponse(Disci_Hekim_Program.IslemServis.IslemOlusturVeIDGetirResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class IslemOlusturVeIDGetirResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int IslemOlusturVeIDGetirResult;
        
        public IslemOlusturVeIDGetirResponseBody() {
        }
        
        public IslemOlusturVeIDGetirResponseBody(int IslemOlusturVeIDGetirResult) {
            this.IslemOlusturVeIDGetirResult = IslemOlusturVeIDGetirResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TariheGoreVeriGetirRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TariheGoreVeriGetir", Namespace="http://tempuri.org/", Order=0)]
        public Disci_Hekim_Program.IslemServis.TariheGoreVeriGetirRequestBody Body;
        
        public TariheGoreVeriGetirRequest() {
        }
        
        public TariheGoreVeriGetirRequest(Disci_Hekim_Program.IslemServis.TariheGoreVeriGetirRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class TariheGoreVeriGetirRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string tarih;
        
        public TariheGoreVeriGetirRequestBody() {
        }
        
        public TariheGoreVeriGetirRequestBody(string tarih) {
            this.tarih = tarih;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TariheGoreVeriGetirResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TariheGoreVeriGetirResponse", Namespace="http://tempuri.org/", Order=0)]
        public Disci_Hekim_Program.IslemServis.TariheGoreVeriGetirResponseBody Body;
        
        public TariheGoreVeriGetirResponse() {
        }
        
        public TariheGoreVeriGetirResponse(Disci_Hekim_Program.IslemServis.TariheGoreVeriGetirResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class TariheGoreVeriGetirResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Disci_Hekim_Program.IslemServis.Islem[] TariheGoreVeriGetirResult;
        
        public TariheGoreVeriGetirResponseBody() {
        }
        
        public TariheGoreVeriGetirResponseBody(Disci_Hekim_Program.IslemServis.Islem[] TariheGoreVeriGetirResult) {
            this.TariheGoreVeriGetirResult = TariheGoreVeriGetirResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IslemListeleRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IslemListele", Namespace="http://tempuri.org/", Order=0)]
        public Disci_Hekim_Program.IslemServis.IslemListeleRequestBody Body;
        
        public IslemListeleRequest() {
        }
        
        public IslemListeleRequest(Disci_Hekim_Program.IslemServis.IslemListeleRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class IslemListeleRequestBody {
        
        public IslemListeleRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IslemListeleResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IslemListeleResponse", Namespace="http://tempuri.org/", Order=0)]
        public Disci_Hekim_Program.IslemServis.IslemListeleResponseBody Body;
        
        public IslemListeleResponse() {
        }
        
        public IslemListeleResponse(Disci_Hekim_Program.IslemServis.IslemListeleResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class IslemListeleResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Disci_Hekim_Program.IslemServis.Islem[] IslemListeleResult;
        
        public IslemListeleResponseBody() {
        }
        
        public IslemListeleResponseBody(Disci_Hekim_Program.IslemServis.Islem[] IslemListeleResult) {
            this.IslemListeleResult = IslemListeleResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IslemlerSoapChannel : Disci_Hekim_Program.IslemServis.IslemlerSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IslemlerSoapClient : System.ServiceModel.ClientBase<Disci_Hekim_Program.IslemServis.IslemlerSoap>, Disci_Hekim_Program.IslemServis.IslemlerSoap {
        
        public IslemlerSoapClient() {
        }
        
        public IslemlerSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IslemlerSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IslemlerSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IslemlerSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Disci_Hekim_Program.IslemServis.GecmisIslemlerResponse Disci_Hekim_Program.IslemServis.IslemlerSoap.GecmisIslemler(Disci_Hekim_Program.IslemServis.GecmisIslemlerRequest request) {
            return base.Channel.GecmisIslemler(request);
        }
        
        public Disci_Hekim_Program.IslemServis.Islem[] GecmisIslemler(int id) {
            Disci_Hekim_Program.IslemServis.GecmisIslemlerRequest inValue = new Disci_Hekim_Program.IslemServis.GecmisIslemlerRequest();
            inValue.Body = new Disci_Hekim_Program.IslemServis.GecmisIslemlerRequestBody();
            inValue.Body.id = id;
            Disci_Hekim_Program.IslemServis.GecmisIslemlerResponse retVal = ((Disci_Hekim_Program.IslemServis.IslemlerSoap)(this)).GecmisIslemler(inValue);
            return retVal.Body.GecmisIslemlerResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Disci_Hekim_Program.IslemServis.GecmisIslemlerResponse> Disci_Hekim_Program.IslemServis.IslemlerSoap.GecmisIslemlerAsync(Disci_Hekim_Program.IslemServis.GecmisIslemlerRequest request) {
            return base.Channel.GecmisIslemlerAsync(request);
        }
        
        public System.Threading.Tasks.Task<Disci_Hekim_Program.IslemServis.GecmisIslemlerResponse> GecmisIslemlerAsync(int id) {
            Disci_Hekim_Program.IslemServis.GecmisIslemlerRequest inValue = new Disci_Hekim_Program.IslemServis.GecmisIslemlerRequest();
            inValue.Body = new Disci_Hekim_Program.IslemServis.GecmisIslemlerRequestBody();
            inValue.Body.id = id;
            return ((Disci_Hekim_Program.IslemServis.IslemlerSoap)(this)).GecmisIslemlerAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Disci_Hekim_Program.IslemServis.IslemOlusturVeIDGetirResponse Disci_Hekim_Program.IslemServis.IslemlerSoap.IslemOlusturVeIDGetir(Disci_Hekim_Program.IslemServis.IslemOlusturVeIDGetirRequest request) {
            return base.Channel.IslemOlusturVeIDGetir(request);
        }
        
        public int IslemOlusturVeIDGetir(int hekimid, int hastaid, string islemadi, string tarih, double toplamtutar) {
            Disci_Hekim_Program.IslemServis.IslemOlusturVeIDGetirRequest inValue = new Disci_Hekim_Program.IslemServis.IslemOlusturVeIDGetirRequest();
            inValue.Body = new Disci_Hekim_Program.IslemServis.IslemOlusturVeIDGetirRequestBody();
            inValue.Body.hekimid = hekimid;
            inValue.Body.hastaid = hastaid;
            inValue.Body.islemadi = islemadi;
            inValue.Body.tarih = tarih;
            inValue.Body.toplamtutar = toplamtutar;
            Disci_Hekim_Program.IslemServis.IslemOlusturVeIDGetirResponse retVal = ((Disci_Hekim_Program.IslemServis.IslemlerSoap)(this)).IslemOlusturVeIDGetir(inValue);
            return retVal.Body.IslemOlusturVeIDGetirResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Disci_Hekim_Program.IslemServis.IslemOlusturVeIDGetirResponse> Disci_Hekim_Program.IslemServis.IslemlerSoap.IslemOlusturVeIDGetirAsync(Disci_Hekim_Program.IslemServis.IslemOlusturVeIDGetirRequest request) {
            return base.Channel.IslemOlusturVeIDGetirAsync(request);
        }
        
        public System.Threading.Tasks.Task<Disci_Hekim_Program.IslemServis.IslemOlusturVeIDGetirResponse> IslemOlusturVeIDGetirAsync(int hekimid, int hastaid, string islemadi, string tarih, double toplamtutar) {
            Disci_Hekim_Program.IslemServis.IslemOlusturVeIDGetirRequest inValue = new Disci_Hekim_Program.IslemServis.IslemOlusturVeIDGetirRequest();
            inValue.Body = new Disci_Hekim_Program.IslemServis.IslemOlusturVeIDGetirRequestBody();
            inValue.Body.hekimid = hekimid;
            inValue.Body.hastaid = hastaid;
            inValue.Body.islemadi = islemadi;
            inValue.Body.tarih = tarih;
            inValue.Body.toplamtutar = toplamtutar;
            return ((Disci_Hekim_Program.IslemServis.IslemlerSoap)(this)).IslemOlusturVeIDGetirAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Disci_Hekim_Program.IslemServis.TariheGoreVeriGetirResponse Disci_Hekim_Program.IslemServis.IslemlerSoap.TariheGoreVeriGetir(Disci_Hekim_Program.IslemServis.TariheGoreVeriGetirRequest request) {
            return base.Channel.TariheGoreVeriGetir(request);
        }
        
        public Disci_Hekim_Program.IslemServis.Islem[] TariheGoreVeriGetir(string tarih) {
            Disci_Hekim_Program.IslemServis.TariheGoreVeriGetirRequest inValue = new Disci_Hekim_Program.IslemServis.TariheGoreVeriGetirRequest();
            inValue.Body = new Disci_Hekim_Program.IslemServis.TariheGoreVeriGetirRequestBody();
            inValue.Body.tarih = tarih;
            Disci_Hekim_Program.IslemServis.TariheGoreVeriGetirResponse retVal = ((Disci_Hekim_Program.IslemServis.IslemlerSoap)(this)).TariheGoreVeriGetir(inValue);
            return retVal.Body.TariheGoreVeriGetirResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Disci_Hekim_Program.IslemServis.TariheGoreVeriGetirResponse> Disci_Hekim_Program.IslemServis.IslemlerSoap.TariheGoreVeriGetirAsync(Disci_Hekim_Program.IslemServis.TariheGoreVeriGetirRequest request) {
            return base.Channel.TariheGoreVeriGetirAsync(request);
        }
        
        public System.Threading.Tasks.Task<Disci_Hekim_Program.IslemServis.TariheGoreVeriGetirResponse> TariheGoreVeriGetirAsync(string tarih) {
            Disci_Hekim_Program.IslemServis.TariheGoreVeriGetirRequest inValue = new Disci_Hekim_Program.IslemServis.TariheGoreVeriGetirRequest();
            inValue.Body = new Disci_Hekim_Program.IslemServis.TariheGoreVeriGetirRequestBody();
            inValue.Body.tarih = tarih;
            return ((Disci_Hekim_Program.IslemServis.IslemlerSoap)(this)).TariheGoreVeriGetirAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Disci_Hekim_Program.IslemServis.IslemListeleResponse Disci_Hekim_Program.IslemServis.IslemlerSoap.IslemListele(Disci_Hekim_Program.IslemServis.IslemListeleRequest request) {
            return base.Channel.IslemListele(request);
        }
        
        public Disci_Hekim_Program.IslemServis.Islem[] IslemListele() {
            Disci_Hekim_Program.IslemServis.IslemListeleRequest inValue = new Disci_Hekim_Program.IslemServis.IslemListeleRequest();
            inValue.Body = new Disci_Hekim_Program.IslemServis.IslemListeleRequestBody();
            Disci_Hekim_Program.IslemServis.IslemListeleResponse retVal = ((Disci_Hekim_Program.IslemServis.IslemlerSoap)(this)).IslemListele(inValue);
            return retVal.Body.IslemListeleResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Disci_Hekim_Program.IslemServis.IslemListeleResponse> Disci_Hekim_Program.IslemServis.IslemlerSoap.IslemListeleAsync(Disci_Hekim_Program.IslemServis.IslemListeleRequest request) {
            return base.Channel.IslemListeleAsync(request);
        }
        
        public System.Threading.Tasks.Task<Disci_Hekim_Program.IslemServis.IslemListeleResponse> IslemListeleAsync() {
            Disci_Hekim_Program.IslemServis.IslemListeleRequest inValue = new Disci_Hekim_Program.IslemServis.IslemListeleRequest();
            inValue.Body = new Disci_Hekim_Program.IslemServis.IslemListeleRequestBody();
            return ((Disci_Hekim_Program.IslemServis.IslemlerSoap)(this)).IslemListeleAsync(inValue);
        }
    }
}
