//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class IslemTablo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IslemTablo()
        {
            this.IslemDetayTablo = new HashSet<IslemDetayTablo>();
        }
    
        public int IslemID { get; set; }
        public Nullable<int> HekimID { get; set; }
        public Nullable<int> HastaID { get; set; }
        public string IslemAdi { get; set; }
        public string Tarih { get; set; }
        public Nullable<double> ToplamTutar { get; set; }
    
        public virtual HastaTablo HastaTablo { get; set; }
        public virtual HekimTablo HekimTablo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IslemDetayTablo> IslemDetayTablo { get; set; }
    }
}
