//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Disci_Hekim_Program.GirisKontrol {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="GirisKontrol.GirisSoap")]
    public interface GirisSoap {
        
        // CODEGEN: Generating message contract since element name kullaniciadi from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GirisKontrol", ReplyAction="*")]
        Disci_Hekim_Program.GirisKontrol.GirisKontrolResponse GirisKontrol(Disci_Hekim_Program.GirisKontrol.GirisKontrolRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GirisKontrol", ReplyAction="*")]
        System.Threading.Tasks.Task<Disci_Hekim_Program.GirisKontrol.GirisKontrolResponse> GirisKontrolAsync(Disci_Hekim_Program.GirisKontrol.GirisKontrolRequest request);
        
        // CODEGEN: Generating message contract since element name mail from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SifreGonder", ReplyAction="*")]
        Disci_Hekim_Program.GirisKontrol.SifreGonderResponse SifreGonder(Disci_Hekim_Program.GirisKontrol.SifreGonderRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SifreGonder", ReplyAction="*")]
        System.Threading.Tasks.Task<Disci_Hekim_Program.GirisKontrol.SifreGonderResponse> SifreGonderAsync(Disci_Hekim_Program.GirisKontrol.SifreGonderRequest request);
        
        // CODEGEN: Generating message contract since element name mail from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MailKontrol", ReplyAction="*")]
        Disci_Hekim_Program.GirisKontrol.MailKontrolResponse MailKontrol(Disci_Hekim_Program.GirisKontrol.MailKontrolRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MailKontrol", ReplyAction="*")]
        System.Threading.Tasks.Task<Disci_Hekim_Program.GirisKontrol.MailKontrolResponse> MailKontrolAsync(Disci_Hekim_Program.GirisKontrol.MailKontrolRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GirisKontrolRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GirisKontrol", Namespace="http://tempuri.org/", Order=0)]
        public Disci_Hekim_Program.GirisKontrol.GirisKontrolRequestBody Body;
        
        public GirisKontrolRequest() {
        }
        
        public GirisKontrolRequest(Disci_Hekim_Program.GirisKontrol.GirisKontrolRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GirisKontrolRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string kullaniciadi;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string sifre;
        
        public GirisKontrolRequestBody() {
        }
        
        public GirisKontrolRequestBody(string kullaniciadi, string sifre) {
            this.kullaniciadi = kullaniciadi;
            this.sifre = sifre;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GirisKontrolResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GirisKontrolResponse", Namespace="http://tempuri.org/", Order=0)]
        public Disci_Hekim_Program.GirisKontrol.GirisKontrolResponseBody Body;
        
        public GirisKontrolResponse() {
        }
        
        public GirisKontrolResponse(Disci_Hekim_Program.GirisKontrol.GirisKontrolResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GirisKontrolResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int GirisKontrolResult;
        
        public GirisKontrolResponseBody() {
        }
        
        public GirisKontrolResponseBody(int GirisKontrolResult) {
            this.GirisKontrolResult = GirisKontrolResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SifreGonderRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SifreGonder", Namespace="http://tempuri.org/", Order=0)]
        public Disci_Hekim_Program.GirisKontrol.SifreGonderRequestBody Body;
        
        public SifreGonderRequest() {
        }
        
        public SifreGonderRequest(Disci_Hekim_Program.GirisKontrol.SifreGonderRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SifreGonderRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string mail;
        
        public SifreGonderRequestBody() {
        }
        
        public SifreGonderRequestBody(string mail) {
            this.mail = mail;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SifreGonderResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SifreGonderResponse", Namespace="http://tempuri.org/", Order=0)]
        public Disci_Hekim_Program.GirisKontrol.SifreGonderResponseBody Body;
        
        public SifreGonderResponse() {
        }
        
        public SifreGonderResponse(Disci_Hekim_Program.GirisKontrol.SifreGonderResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SifreGonderResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SifreGonderResult;
        
        public SifreGonderResponseBody() {
        }
        
        public SifreGonderResponseBody(string SifreGonderResult) {
            this.SifreGonderResult = SifreGonderResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MailKontrolRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MailKontrol", Namespace="http://tempuri.org/", Order=0)]
        public Disci_Hekim_Program.GirisKontrol.MailKontrolRequestBody Body;
        
        public MailKontrolRequest() {
        }
        
        public MailKontrolRequest(Disci_Hekim_Program.GirisKontrol.MailKontrolRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MailKontrolRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string mail;
        
        public MailKontrolRequestBody() {
        }
        
        public MailKontrolRequestBody(string mail) {
            this.mail = mail;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MailKontrolResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MailKontrolResponse", Namespace="http://tempuri.org/", Order=0)]
        public Disci_Hekim_Program.GirisKontrol.MailKontrolResponseBody Body;
        
        public MailKontrolResponse() {
        }
        
        public MailKontrolResponse(Disci_Hekim_Program.GirisKontrol.MailKontrolResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MailKontrolResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool MailKontrolResult;
        
        public MailKontrolResponseBody() {
        }
        
        public MailKontrolResponseBody(bool MailKontrolResult) {
            this.MailKontrolResult = MailKontrolResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface GirisSoapChannel : Disci_Hekim_Program.GirisKontrol.GirisSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GirisSoapClient : System.ServiceModel.ClientBase<Disci_Hekim_Program.GirisKontrol.GirisSoap>, Disci_Hekim_Program.GirisKontrol.GirisSoap {
        
        public GirisSoapClient() {
        }
        
        public GirisSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GirisSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GirisSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GirisSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Disci_Hekim_Program.GirisKontrol.GirisKontrolResponse Disci_Hekim_Program.GirisKontrol.GirisSoap.GirisKontrol(Disci_Hekim_Program.GirisKontrol.GirisKontrolRequest request) {
            return base.Channel.GirisKontrol(request);
        }
        
        public int GirisKontrol(string kullaniciadi, string sifre) {
            Disci_Hekim_Program.GirisKontrol.GirisKontrolRequest inValue = new Disci_Hekim_Program.GirisKontrol.GirisKontrolRequest();
            inValue.Body = new Disci_Hekim_Program.GirisKontrol.GirisKontrolRequestBody();
            inValue.Body.kullaniciadi = kullaniciadi;
            inValue.Body.sifre = sifre;
            Disci_Hekim_Program.GirisKontrol.GirisKontrolResponse retVal = ((Disci_Hekim_Program.GirisKontrol.GirisSoap)(this)).GirisKontrol(inValue);
            return retVal.Body.GirisKontrolResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Disci_Hekim_Program.GirisKontrol.GirisKontrolResponse> Disci_Hekim_Program.GirisKontrol.GirisSoap.GirisKontrolAsync(Disci_Hekim_Program.GirisKontrol.GirisKontrolRequest request) {
            return base.Channel.GirisKontrolAsync(request);
        }
        
        public System.Threading.Tasks.Task<Disci_Hekim_Program.GirisKontrol.GirisKontrolResponse> GirisKontrolAsync(string kullaniciadi, string sifre) {
            Disci_Hekim_Program.GirisKontrol.GirisKontrolRequest inValue = new Disci_Hekim_Program.GirisKontrol.GirisKontrolRequest();
            inValue.Body = new Disci_Hekim_Program.GirisKontrol.GirisKontrolRequestBody();
            inValue.Body.kullaniciadi = kullaniciadi;
            inValue.Body.sifre = sifre;
            return ((Disci_Hekim_Program.GirisKontrol.GirisSoap)(this)).GirisKontrolAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Disci_Hekim_Program.GirisKontrol.SifreGonderResponse Disci_Hekim_Program.GirisKontrol.GirisSoap.SifreGonder(Disci_Hekim_Program.GirisKontrol.SifreGonderRequest request) {
            return base.Channel.SifreGonder(request);
        }
        
        public string SifreGonder(string mail) {
            Disci_Hekim_Program.GirisKontrol.SifreGonderRequest inValue = new Disci_Hekim_Program.GirisKontrol.SifreGonderRequest();
            inValue.Body = new Disci_Hekim_Program.GirisKontrol.SifreGonderRequestBody();
            inValue.Body.mail = mail;
            Disci_Hekim_Program.GirisKontrol.SifreGonderResponse retVal = ((Disci_Hekim_Program.GirisKontrol.GirisSoap)(this)).SifreGonder(inValue);
            return retVal.Body.SifreGonderResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Disci_Hekim_Program.GirisKontrol.SifreGonderResponse> Disci_Hekim_Program.GirisKontrol.GirisSoap.SifreGonderAsync(Disci_Hekim_Program.GirisKontrol.SifreGonderRequest request) {
            return base.Channel.SifreGonderAsync(request);
        }
        
        public System.Threading.Tasks.Task<Disci_Hekim_Program.GirisKontrol.SifreGonderResponse> SifreGonderAsync(string mail) {
            Disci_Hekim_Program.GirisKontrol.SifreGonderRequest inValue = new Disci_Hekim_Program.GirisKontrol.SifreGonderRequest();
            inValue.Body = new Disci_Hekim_Program.GirisKontrol.SifreGonderRequestBody();
            inValue.Body.mail = mail;
            return ((Disci_Hekim_Program.GirisKontrol.GirisSoap)(this)).SifreGonderAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Disci_Hekim_Program.GirisKontrol.MailKontrolResponse Disci_Hekim_Program.GirisKontrol.GirisSoap.MailKontrol(Disci_Hekim_Program.GirisKontrol.MailKontrolRequest request) {
            return base.Channel.MailKontrol(request);
        }
        
        public bool MailKontrol(string mail) {
            Disci_Hekim_Program.GirisKontrol.MailKontrolRequest inValue = new Disci_Hekim_Program.GirisKontrol.MailKontrolRequest();
            inValue.Body = new Disci_Hekim_Program.GirisKontrol.MailKontrolRequestBody();
            inValue.Body.mail = mail;
            Disci_Hekim_Program.GirisKontrol.MailKontrolResponse retVal = ((Disci_Hekim_Program.GirisKontrol.GirisSoap)(this)).MailKontrol(inValue);
            return retVal.Body.MailKontrolResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Disci_Hekim_Program.GirisKontrol.MailKontrolResponse> Disci_Hekim_Program.GirisKontrol.GirisSoap.MailKontrolAsync(Disci_Hekim_Program.GirisKontrol.MailKontrolRequest request) {
            return base.Channel.MailKontrolAsync(request);
        }
        
        public System.Threading.Tasks.Task<Disci_Hekim_Program.GirisKontrol.MailKontrolResponse> MailKontrolAsync(string mail) {
            Disci_Hekim_Program.GirisKontrol.MailKontrolRequest inValue = new Disci_Hekim_Program.GirisKontrol.MailKontrolRequest();
            inValue.Body = new Disci_Hekim_Program.GirisKontrol.MailKontrolRequestBody();
            inValue.Body.mail = mail;
            return ((Disci_Hekim_Program.GirisKontrol.GirisSoap)(this)).MailKontrolAsync(inValue);
        }
    }
}
